% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{fontspec}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{colortbl}
\usepackage{hhline}
\newlength\Oldarrayrulewidth
\newlength\Oldtabcolsep
\usepackage{longtable}
\usepackage{array}
\usepackage{hyperref}
\usepackage{float}
\usepackage{wrapfig}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Reliability and Validity}\label{reliability-and-validity}

For this chapter we refer to the book
\href{https://www.cambridge.org/core/books/measurement-in-medicine/8BD913A1DA0ECCBA951AC4C1F719BCC5}{Measurement in Medicine}.

I invite you to read the introductory chapters 1 and 2 about concepts,
theories and models, and types of measurement.

In general, when conducting a measurement of any sort
(laboratory measurements, scores from questionnaires, etc.),
we want to be reasonably sure

\begin{itemize}
\tightlist
\item
  that we actually \textbf{measure what we intend to measure};
  (\href{https://en.wikipedia.org/wiki/Validity_(statistics)}{validity};
  chapter 6 in the book);
\item
  that the measurement does \textbf{not change too much} if the
  underlying \textbf{conditions are the same}
  (\href{https://en.wikipedia.org/wiki/Reliability_(statistics)}{reliability};
  chapter 5 in the book); and
\item
  that we are able to detect a \textbf{change} if the underlying conditions change
  (\href{https://tinyurl.com/3vdcxy49}{responsiveness}; chapter 7 in the book); and
\item
  that we understand the meaning of a change in the measurement
  (interpretability; chapter 8 in the book).
\end{itemize}

In this \href{https://www.youtube.com/watch?v=KuT2n1w0Ixc&ab_channel=Physiotutors}{video},
Kai jump starts you on reliability and validity.

\subsection{Reliability}\label{reliability}

You can watch this \href{https://www.youtube.com/watch?v=9HSoWaRpcys&ab_channel=Physiotutors}{video}
to get started.

Imagine, you measure a patient (pick your favorite measurement), for example,
the range of motion (ROM) of the shoulder.

\begin{itemize}
\tightlist
\item
  If you are interested in how
  similar your measurements are in comparison to your colleagues, you are
  trying to determine the so-called \textbf{inter-rater reliability}.
\item
  If you are interested in how similar your measurements are when you measure
  the same patient twice, you are trying to determine the so-called
  \textbf{intra-rater reliability}.
\end{itemize}

Assuming there is a true (but unknown) underlying value (of Range of Motion, ROM),
it is clear that measurements will not be \emph{exactly} the same.
Possible influences (potentially) causing different results are:

\begin{itemize}
\tightlist
\item
  the measurement instrument itself,
\item
  the patient (e.g., mood/motivation),
\item
  the examiner (e.g., mood/focus, influence on patient, interpretation of decision rules),
\item
  the environment (e.g., the room temperature).
\end{itemize}

Note that the \textbf{true score} is defined in our context as the \textbf{average}
of all measurements if we would measure repeatedly an infinite number of times (p.98).
In this sense, one can measure the \textbf{true score} (in principle, not in practice)
arbitrarily well.

\subsubsection{Peter and Mary's ROM measurements}\label{peter-and-marys-rom-measurements}

The data can be found \href{http://www.clinimetrics.nl/answers-to-the-assignments-in-textbook_22_0.html}{here}.
We randomly select 50 measurements from Peter and Mary in 50 different patients,
plot their measurements and annotate the absolutely largest one(s). At first the
\emph{not affected shoulder} (nas) and then the \emph{affected shoulder} (as).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(pacman)}
\FunctionTok{p\_load}\NormalTok{(tidyverse, readxl)}

\CommentTok{\# Read file}
\NormalTok{url }\OtherTok{\textless{}{-}} \StringTok{"https://raw.githubusercontent.com/jdegenfellner/Script\_QM2\_ZHAW/main/data/chapter\%205\_assignment\%201\_2\_wide.xls"}
\NormalTok{temp\_file }\OtherTok{\textless{}{-}} \FunctionTok{tempfile}\NormalTok{(}\AttributeTok{fileext =} \StringTok{".xls"}\NormalTok{)}
\FunctionTok{download.file}\NormalTok{(url, temp\_file, }\AttributeTok{mode =} \StringTok{"wb"}\NormalTok{)  }\CommentTok{\# mode="wb" is important for binary files}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(temp\_file)}

\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##   patcode ROMnas.Mary ROMnas.Peter ROMas.Mary ROMas.Peter
##     <dbl>       <dbl>        <dbl>      <dbl>       <dbl>
## 1       1          90           92         88          95
## 2       2          82           88         82          90
## 3       3          82           88         57          59
## 4       4          89           89         82          81
## 5       5          80           82         48          40
## 6       6          90           96         99          85
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 155   5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# As in the book, let\textquotesingle{}s randomly select 50 patients.}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{sample\_n}\NormalTok{(}\DecValTok{50}\NormalTok{)}
\FunctionTok{dim}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 50  5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# "as" = affected shoulder}
\CommentTok{\# "nas" = not affected shoulder}

\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{mutate}\NormalTok{(}\AttributeTok{diff =} \FunctionTok{abs}\NormalTok{(ROMnas.Peter }\SpecialCharTok{{-}}\NormalTok{ ROMnas.Mary))  }\CommentTok{\# Compute absolute difference}

\NormalTok{max\_diff\_point }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(diff }\SpecialCharTok{==} \FunctionTok{max}\NormalTok{(diff, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))  }\CommentTok{\# Find the row with the max difference}

\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ ROMnas.Peter, }\AttributeTok{y =}\NormalTok{ ROMnas.Mary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{data =}\NormalTok{ max\_diff\_point, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ ROMnas.Peter, }\AttributeTok{y =}\NormalTok{ ROMnas.Mary), }
             \AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{4}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Highlight max difference point}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"ROMnas.Peter vs. ROMnas.Mary"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =}\NormalTok{ max\_diff\_point}\SpecialCharTok{$}\NormalTok{ROMnas.Peter, }
           \AttributeTok{y =}\NormalTok{ max\_diff\_point}\SpecialCharTok{$}\NormalTok{ROMnas.Mary, }
           \AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Max Diff: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(max\_diff\_point}\SpecialCharTok{$}\NormalTok{diff, }\DecValTok{2}\NormalTok{)), }
           \AttributeTok{vjust =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-1-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# average abs. difference:}
\FunctionTok{mean}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{diff, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\CommentTok{\# 7.2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{ROMnas.Peter, df}\SpecialCharTok{$}\NormalTok{ROMnas.Mary, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2403213
\end{verbatim}

The red line represents the line of equality (\(y=x\)). If the measurements are
exactly the same,
all points would lie on this line (\(\rho=1\)). The blue point represents the measurement with the largest
absolute difference in measured Range of Motion (ROM) values between Peter and Mary
from the randomly chosen 50 people. Note that the maximum difference in
all 155 patients is even higher with 35 degrees.

The first simple measure of agreement we could use is the \href{https://en.wikipedia.org/wiki/Pearson_correlation_coefficient}{(Pearson) correlation},
which measures the \textbf{strength and direction of a linear relationship between two variables}.
But correlation does not exactly measure what we want. If there was a bias
(e.g., Mary systematically measures 5 degrees more than Peter), correlation would not
notice this (\hyperref[exercise1]{exercise 1}). It actually is too optimistic about
the agreement since it only cares about the linearity and not about a potential bias:
\(r=0.2403213\) which indicates a weak positive correlation. Higher values of Peter's measurements
are associated with higher values of Mary's measurements.
But: Knowing Peter's measurement does not help us to
\href{https://en.wikipedia.org/wiki/Pearson_correlation_coefficient\#Interpretation_of_the_size_of_a_correlation}{\emph{predict}}
Mary's measurement at such a low correlation (\hyperref[exercise2]{exercise 2}).
So, on the \emph{not affected shoulder} (nas), agreement is really bad.

\textbf{What about the affected shoulder (as)?}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggExtra)}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{diff =} \FunctionTok{abs}\NormalTok{(ROMas.Peter }\SpecialCharTok{{-}}\NormalTok{ ROMas.Mary))  }\CommentTok{\# Compute absolute difference}

\NormalTok{max\_diff\_point }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(diff }\SpecialCharTok{==} \FunctionTok{max}\NormalTok{(diff, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))  }\CommentTok{\# Find the row with the max difference}

\NormalTok{p }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ ROMas.Peter, }\AttributeTok{y =}\NormalTok{ ROMas.Mary)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{data =}\NormalTok{ max\_diff\_point, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ ROMas.Peter, }\AttributeTok{y =}\NormalTok{ ROMas.Mary), }
             \AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{4}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Highlight max difference point}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"ROMas.Peter vs. ROMas.Mary"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =}\NormalTok{ max\_diff\_point}\SpecialCharTok{$}\NormalTok{ROMas.Peter, }
           \AttributeTok{y =}\NormalTok{ max\_diff\_point}\SpecialCharTok{$}\NormalTok{ROMas.Mary, }
           \AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Max Diff: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(max\_diff\_point}\SpecialCharTok{$}\NormalTok{diff, }\DecValTok{2}\NormalTok{)), }
           \AttributeTok{vjust =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{4}\NormalTok{)}
\CommentTok{\# Add marginal histograms}
\FunctionTok{ggMarginal}\NormalTok{(p, }\AttributeTok{type =} \StringTok{"density"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"gray"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-2-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# average abs. difference:}
\FunctionTok{mean}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{diff, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\CommentTok{\# 7.2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.78
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{ROMas.Peter, df}\SpecialCharTok{$}\NormalTok{ROMas.Mary, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8516653
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# mean difference}
\FunctionTok{mean}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{ROMas.Peter }\SpecialCharTok{{-}}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{ROMas.Mary, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.22
\end{verbatim}

In the affected side, the average absolute difference is even larger (\(7.78\))
with a maximum absolute difference of \(37\) degrees (on the whole sample of \(155\) patients),
but the correlation is much higher (\(r=0.8516653\)). See Figure 5.2 in the book.

This is an occasion for using the correlation coefficient even though
the marginal distributions are not normal: There are much more measurements in the higher
values around \(80\) than below, say, \(60\). But the correlation coefficient makes sense
for descriptive purposes.

In this case, knowing Peter's measurement \emph{does} (at least somewhat) help us to predict
Mary's measurement (see \hyperref[badnews]{below}).

\subsubsection{Intraclass Correlation Coefficient (ICC)}\label{ICC}

One way to measure reliability is to use the
\href{https://en.wikipedia.org/wiki/Intraclass_correlation}{intraclass correlation coefficient (ICC)}.

This measure is based on the idea that the observed score \(Y_i\) consists of the true score
(ROM) (\(\eta_i\)) and a measurement error (for each person).
The proportion of the true score variability to the total variability is the ICC.

In the background one thinks of a statistical model from the
\href{https://en.wikipedia.org/wiki/Classical_test_theory}{Classical Test Theory (CTT)}.
There is

\begin{itemize}
\tightlist
\item
  a true underlying score \(\eta_i\) (for each patient \(i\)) and
\item
  an error term \(\varepsilon_i \sim N(0, \sigma_i)\) which is the difference between the true
  score and
\item
  the observed score \(Y_i\).
\end{itemize}

\[Y_i = \eta_i + \varepsilon_i\]

It is assumed that \(\eta_i\) and \(\varepsilon_i\) are independent: (\(\mathbb{C}ov(\eta_i, \varepsilon_i)=0\)).
This is a convenient assumption because now we know (see \href{https://en.wikipedia.org/wiki/Variance\#Addition_and_multiplication_by_a_constant}{here})
that the variance
of the observed score \(Y_i\) is just the sum of the variance of the true score \(\eta_i\)
and the variance of the error term \(\varepsilon_i\):

\[\mathbb{V}ar(Y_i) = \mathbb{V}ar(\eta_i) + \mathbb{V}ar(\varepsilon_i)\]
\[\sigma_{Y_i}^2 = \sigma_{\eta_i}^2 + \sigma_{\varepsilon_i}^2\]

We want most of the variability (i.e.~how much scores in our relevant population vary)
in our observed scores \(Y_i\) to be explained by the
true but (directly) unobservable scores \(\eta_i\). The measurement error \(\varepsilon_i\) should be
be comparatively small (and of course on average \(0\)). If it is large, we are mostly measuring noise or at least not
what we want to measure.

\textbf{How do we get to the theoretical definition of the ICC?}

If you either pull two people with the same true but unobservable score \(\eta\) out of the population
or measure the same person twice and the score (\(\eta\)) does not change in between, we can
\textbf{define reliability as correlation between these two measurements}:

\[Y_1 = \eta + \varepsilon_1\]
\[Y_2 = \eta + \varepsilon_2\]

\[cor(Y_1, Y_2) = cor(\eta + \varepsilon_1, \eta + \varepsilon_2) = \frac{Cov(\eta + \varepsilon_1, \eta + \varepsilon_2)}{\sigma_{Y_1}\sigma_{Y_2}}  =\]

If we use

\begin{itemize}
\tightlist
\item
  the \href{https://en.wikipedia.org/wiki/Covariance\#Properties}{properties of the covariance},
\item
  the fact that the true score \(\eta\) and the errors \(\varepsilon_i\) are independent, and
\item
  the fact that the errors \(\varepsilon_1\) and \(\varepsilon_2\) are independent, we get:
\end{itemize}

\[\frac{Cov(\eta, \eta) + Cov(\eta, \varepsilon_2) + Cov(\varepsilon_1, \eta) + Cov(\varepsilon_1, \varepsilon_2)}{\sigma_{Y_1} \sigma_{Y_2}}  =\]
\[\frac{\sigma_{\eta}^2 + 0 + 0 + 0}{\sigma_{Y_1} \sigma_{Y_2}}\]

Since \(\eta\) is a random variable (we draw a person randomly from the population),
it is well defined to talk about the variance of \(\eta\) (i.e., \(\sigma_{\eta}^2\)).
I think this aspect may not come across in the book quite so clearly.

Furthermore, it does not matter if I call the measurement \(Y_1\), \(Y_2\) or more general
\(Y\), since they have the same variance and true score:

\[\sigma_{Y} = \sigma_{Y_1} = \sigma_{Y_2}\]

Hence, it follows that:

\[cor(Y_1, Y_2) = \frac{\sigma_{\eta}^2}{\sigma_{Y_1}^2} = \frac{\sigma_{\eta}^2}{\sigma_{Y}^2} =  \frac{\sigma_{\eta}^2}{\sigma_{Y}^2} = \frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 + \sigma_{\varepsilon}^2}\]

This is the \textbf{intraclass correlation coefficient (ICC)}.
It is (as seen in the formula above) the proportion of the
true score variability to the total variability.
It ranges from 0 and 1 (think about why!).

A little manipulation to improve understanding:

Let's look again at the term for the ICC above and divide the numerator and the denominator by
\(\sigma_{\eta}^2\), which we can do, since it is a positive number:

\[\frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 + \sigma_{\varepsilon}^2} = \frac{1}{1 + \frac{\sigma_{\varepsilon}^2}{\sigma_{\eta}^2}}\]

We could call the term \(\frac{\sigma_{\varepsilon}^2}{\sigma_{\eta}^2}\) the noise-to-signal ratio.
The higher this ratio, the lower the ICC. The lower the ratio, the higher the ICC.

\begin{itemize}
\tightlist
\item
  If you increase the noise (measurement error \(\sigma_{\varepsilon}^2\)) for fixed
  true score variability \(\sigma_{\eta}^2\), the ICC decreases, because the denominator
  increases.
\item
  If you increase the true score variability \(\sigma_{\eta}^2\) for fixed noise \(\sigma_{\varepsilon}^2\),
  the ICC increases, since the denominator decreases.
\end{itemize}

Btw, we could also divide by \(\sigma_{\varepsilon}^2\) and get the \textbf{signal-to-noise ratio}.

At first glance, the following statement seems wrong:

In a very \textbf{homogeneous population} (patients have very similar scores/measurements),
the \textbf{ICC might be very low}. The reason is that the patient variability \(\sigma_{\eta}^2\) is low
and you probably have some measurement error \(\sigma_{\varepsilon}^2\).
Hence, if you look at the formula, ICC must be low (for a given measurement error).

On the other hand, if you have a very \textbf{heterogeneous population} (patients have rather different
scores/measurements), the \textbf{ICC might be very high}.
The reason is that the patient variability \(\sigma_{\eta}^2\) is high and you probably
have some measurement error \(\sigma_{\varepsilon}^2\).

\textbf{What matters is the ratio of the two}, as can be seen from the formula above.

Let's try to calculate the ICC for our data using a statistical model. There are a couple of different
R packages to do this. We start by using the \texttt{irr} package.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(irr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lpSolve
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{irr}\SpecialCharTok{::}\FunctionTok{icc}\NormalTok{(}\FunctionTok{as.matrix}\NormalTok{(df[, }\FunctionTok{c}\NormalTok{(}\StringTok{"ROMas.Peter"}\NormalTok{, }\StringTok{"ROMas.Mary"}\NormalTok{)]), }
    \AttributeTok{model =} \StringTok{"oneway"}\NormalTok{, }\AttributeTok{type =} \StringTok{"consistency"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Single Score Intraclass Correlation
## 
##    Model: oneway 
##    Type : consistency 
## 
##    Subjects = 50 
##      Raters = 2 
##      ICC(1) = 0.851
## 
##  F-Test, H0: r0 = 0 ; H1: r0 > 0 
##    F(49,50) = 12.4 , p = 7.31e-16 
## 
##  95%-Confidence Interval for ICC Population Values:
##   0.753 < ICC < 0.913
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor.test}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{ROMas.Peter, df}\SpecialCharTok{$}\NormalTok{ROMas.Mary, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  df$ROMas.Peter and df$ROMas.Mary
## t = 11.259, df = 48, p-value = 4.538e-15
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7514574 0.9134673
## sample estimates:
##       cor 
## 0.8516653
\end{verbatim}

We get the result: \(ICC(1) = 0.851\), which is identical to the correlation coefficient
because there is no systematic difference between Peter and Mary.

Since \textbf{we are forward looking and modern regression model experts},
we would like to see if we can get (approximately) the same result using the Bayesian
framework.

Below is the model structure (see \hyperref[exercise3]{exercise 3}).

\[
\begin{array}{rcl}
ROM_i &\sim& N(\mu_i, \sigma_{\varepsilon}) \\
\mu_i &=& \alpha[ID] \\
\alpha[ID] &\sim& \text{Normal}(\mu_{\alpha}, \sigma_{\alpha}) \\
\mu_{\alpha} &\sim& \text{Normal}(66, 20) \\
\sigma_{\alpha} &\sim& \text{Uniform}(0,20) \\
\sigma_{\varepsilon} &\sim& \text{Uniform}(0,20)
\end{array}
\]

\textbf{Model details:}

\begin{itemize}
\tightlist
\item
  \(ROM_i\) is the observed \(ROM\)-score for patient \(i\). Currently, we have chosen the \emph{ROMs} to
  come from a normal distribution. As we have seen above, this might not be adequate,
  since the marginal distributions look skewed.
  Every patient has two observations (one each from Mary and Peter).
  So, for instance \(i=1,2\) could be patient \(ID=1\).
\item
  \(\mu_i\) is the expected value of the observed score for patient \(ID\).
\item
  \(\sigma_{\varepsilon}\) is the standard deviation of the measurement error.
\item
  \(\alpha[ID]\) is the patient-specific intercept (\(=\eta_i\)).
  Since every patient is allowed to have a different intercept,
  we have a \textbf{random intercepts model}.
  The intercepts are drawn from a normal distribution (hence, \emph{random})
\item
  \(\mu_{\alpha}\) is the mean of the prior for the patient-specific intercepts.
  This is the overall mean of the scores.
\item
  \(\sigma_{\alpha}\) is the standard deviation of the patient-specific intercepts.
  \textbf{This is the patient variability}! \(\sigma_{\alpha}\) controls how much
  the scores of the patients may vary.
  In the extreme cases \(\sigma_{\alpha} \rightarrow 0\) and \(\sigma_{\alpha} \rightarrow \infty\),
  we have \emph{complete-pooling} (all \(\mu_i\) are identical) and \emph{no-pooling}
  (all \(\mu_i\) are different and there is no shared information), respectively.
  We are using \textbf{partial pooling} here.
\item
  The prior distributions express (as always) our prior beliefs about the parameters.
\end{itemize}

The \textbf{ICC} is then calculated as the ratio of the between-patient variance and
the total variance:

\[\frac{\sigma_{\alpha}^2}{\sigma_{\alpha}^2 + \sigma_{\varepsilon}^2}\]

We did not even notice it, but this was our first \textbf{multilevel regression model}.
It is multilevel due to the extra layer of patient-specific intercepts.
The \textbf{observations} are obviously \textbf{clustered within patients}, since observations
from the \textbf{same patient} are \textbf{more similar than observations from different patients}.
If one would run a normal linear regression model, one would ignore this clustering
and the assumption of independent error terms would be violated.

This time we fire up the \texttt{rethinking} package and use the \texttt{ulam} function
to fit the model.
This uses Markov Chain Monte Carlo (MCMC) to sample from the posterior
distribution of the parameters.

\begin{itemize}
\item
  The \texttt{chains} argument specifies how many chains we want to run.
  A \emph{chain} is a sequence of points in a space with as many dimensions as there
  are parameters in the model. It jumps from one point to the next in this parameter
  space and in doing so, visits the points of the posterior approximately in the correct
  frequency. \href{https://blog.revolutionanalytics.com/2013/09/an-animated-peek-into-the-workings-of-bayesian-statistics.html}{Here}
  is an excellent visualization.
\item
  The \texttt{cores} argument specifies how many CPU cores we want to use.
  For larger jobs, one can try to parallelize
  the chains, which saves some time.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rethinking)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: cmdstanr
\end{verbatim}

\begin{verbatim}
## This is cmdstanr version 0.8.1.9000
\end{verbatim}

\begin{verbatim}
## - CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
\end{verbatim}

\begin{verbatim}
## - CmdStan path: /Users/juergen/.cmdstan/cmdstan-2.36.0
\end{verbatim}

\begin{verbatim}
## - CmdStan version: 2.36.0
\end{verbatim}

\begin{verbatim}
## Loading required package: posterior
\end{verbatim}

\begin{verbatim}
## This is posterior version 1.6.1
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'posterior'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     mad, sd, var
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     %in%, match
\end{verbatim}

\begin{verbatim}
## Loading required package: parallel
\end{verbatim}

\begin{verbatim}
## rethinking (Version 2.42)
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'rethinking'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     map
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:stats':
## 
##     rstudent
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tictoc)}

\NormalTok{df\_long }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{ID =} \FunctionTok{row\_number}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(ID,ROMas.Peter, ROMas.Mary) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols =} \FunctionTok{c}\NormalTok{(ROMas.Peter, ROMas.Mary), }
               \AttributeTok{names\_to =} \StringTok{"Rater"}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{"ROM"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Rater =} \FunctionTok{factor}\NormalTok{(Rater))}

\FunctionTok{tic}\NormalTok{()}
\NormalTok{m5}\FloatTok{.1} \OtherTok{\textless{}{-}} \FunctionTok{ulam}\NormalTok{(}
  \FunctionTok{alist}\NormalTok{(}
    \CommentTok{\# Likelihood}
\NormalTok{    ROM }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(mu, sigma),}
    
    \CommentTok{\# Patient{-}specific intercepts (random effects)}
\NormalTok{    mu }\OtherTok{\textless{}{-}}\NormalTok{ a[ID],  }
\NormalTok{    a[ID] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(mu\_a, sigma\_ID),  }\CommentTok{\# Hierarchical structure for patients}
    
    \CommentTok{\# Priors for hyperparameters}
\NormalTok{    mu\_a }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(}\DecValTok{66}\NormalTok{, }\DecValTok{20}\NormalTok{),  }\CommentTok{\# Population{-}level mean}
\NormalTok{    sigma\_ID }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dunif}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{20}\NormalTok{),  }\CommentTok{\# Between{-}patient standard deviation}
\NormalTok{    sigma }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dunif}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{20}\NormalTok{)  }\CommentTok{\# Residual standard deviation}
\NormalTok{  ), }
  \AttributeTok{data =}\NormalTok{ df\_long, }
  \AttributeTok{chains =} \DecValTok{8}\NormalTok{, }\AttributeTok{cores =} \DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Running MCMC with 8 chains, at most 4 in parallel, with 1 thread(s) per chain...
## 
## Chain 1 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 1 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 1 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 1 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 1 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 1 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 1 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 1 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 1 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 1 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 1 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 1 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 2 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 2 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 2 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 2 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 2 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 2 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 2 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 3 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 3 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 3 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 3 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 3 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 3 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 3 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 3 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 3 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 3 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 3 Iteration: 900 / 1000 [ 90%]  (Sampling)
\end{verbatim}

\begin{verbatim}
## Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
\end{verbatim}

\begin{verbatim}
## Chain 3 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d7d9a069a.stan', line 17, column 4 to column 34)
\end{verbatim}

\begin{verbatim}
## Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
\end{verbatim}

\begin{verbatim}
## Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
\end{verbatim}

\begin{verbatim}
## Chain 3
\end{verbatim}

\begin{verbatim}
## Chain 4 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 4 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 4 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 4 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 4 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 4 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 4 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 4 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 4 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 4 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 4 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 4 Iteration: 1000 / 1000 [100%]  (Sampling)
\end{verbatim}

\begin{verbatim}
## Chain 4 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
\end{verbatim}

\begin{verbatim}
## Chain 4 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d7d9a069a.stan', line 17, column 4 to column 34)
\end{verbatim}

\begin{verbatim}
## Chain 4 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
\end{verbatim}

\begin{verbatim}
## Chain 4 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
\end{verbatim}

\begin{verbatim}
## Chain 4
\end{verbatim}

\begin{verbatim}
## Chain 1 finished in 0.1 seconds.
## Chain 3 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 3 finished in 0.2 seconds.
## Chain 4 finished in 0.1 seconds.
## Chain 2 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 2 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 2 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 2 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 2 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 5 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 5 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 5 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 5 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 5 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 5 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 5 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 5 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 5 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 5 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 5 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 5 Iteration: 1000 / 1000 [100%]  (Sampling)
\end{verbatim}

\begin{verbatim}
## Chain 5 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
\end{verbatim}

\begin{verbatim}
## Chain 5 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d7d9a069a.stan', line 17, column 4 to column 34)
\end{verbatim}

\begin{verbatim}
## Chain 5 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
\end{verbatim}

\begin{verbatim}
## Chain 5 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
\end{verbatim}

\begin{verbatim}
## Chain 5
\end{verbatim}

\begin{verbatim}
## Chain 6 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 6 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 6 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 6 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 6 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 6 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 6 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 6 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 6 Iteration: 700 / 1000 [ 70%]  (Sampling)
\end{verbatim}

\begin{verbatim}
## Chain 6 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
\end{verbatim}

\begin{verbatim}
## Chain 6 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d7d9a069a.stan', line 17, column 4 to column 34)
\end{verbatim}

\begin{verbatim}
## Chain 6 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
\end{verbatim}

\begin{verbatim}
## Chain 6 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
\end{verbatim}

\begin{verbatim}
## Chain 6
\end{verbatim}

\begin{verbatim}
## Chain 7 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 7 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 7 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 7 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 7 Iteration: 400 / 1000 [ 40%]  (Warmup)
\end{verbatim}

\begin{verbatim}
## Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
\end{verbatim}

\begin{verbatim}
## Chain 7 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d7d9a069a.stan', line 17, column 4 to column 34)
\end{verbatim}

\begin{verbatim}
## Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
\end{verbatim}

\begin{verbatim}
## Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
\end{verbatim}

\begin{verbatim}
## Chain 7
\end{verbatim}

\begin{verbatim}
## Chain 2 finished in 0.2 seconds.
## Chain 5 finished in 0.1 seconds.
## Chain 6 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 6 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 6 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 7 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 7 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 7 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 7 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 7 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 7 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 7 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 8 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 8 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 8 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 8 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 8 Iteration: 400 / 1000 [ 40%]  (Warmup)
\end{verbatim}

\begin{verbatim}
## Chain 8 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
\end{verbatim}

\begin{verbatim}
## Chain 8 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d7d9a069a.stan', line 17, column 4 to column 34)
\end{verbatim}

\begin{verbatim}
## Chain 8 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
\end{verbatim}

\begin{verbatim}
## Chain 8 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
\end{verbatim}

\begin{verbatim}
## Chain 8
\end{verbatim}

\begin{verbatim}
## Chain 6 finished in 0.1 seconds.
## Chain 7 finished in 0.1 seconds.
## Chain 8 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 8 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 8 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 8 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 8 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 8 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 8 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 8 finished in 0.1 seconds.
## 
## All 8 chains finished successfully.
## Mean chain execution time: 0.1 seconds.
## Total execution time: 0.6 seconds.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{toc}\NormalTok{() }\CommentTok{\# 7s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 6.923 sec elapsed
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{precis}\NormalTok{(m5}\FloatTok{.1}\NormalTok{, }\AttributeTok{depth =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               mean       sd     5.5%    94.5%      rhat ess_bulk
## a[1]     67.801401 4.851443 60.13017 75.60306 1.0024139 6619.991
## a[2]     64.190684 4.841765 56.47704 71.96682 1.0033561 6087.696
## a[3]     86.996738 4.736453 79.48393 94.60960 0.9993506 6369.422
## a[4]     76.530318 4.831713 68.84843 84.38513 1.0018190 5157.235
## a[5]     58.776451 4.765509 51.22798 66.39053 1.0018377 5098.476
## a[6]     69.128605 4.965425 61.20783 77.06063 1.0042993 4789.658
## a[7]     69.701335 4.763945 62.04819 77.27248 1.0031944 5659.441
## a[8]     67.333150 4.833474 59.61635 74.95783 1.0013529 5670.597
## a[9]     71.032050 4.905078 63.27131 78.81170 1.0023262 5977.332
## a[10]    80.899118 4.778177 73.26061 88.45832 1.0034929 5550.457
## a[11]    70.487119 4.890308 62.66053 78.19115 1.0024445 7088.019
## a[12]    42.225071 4.891742 34.40218 49.92050 1.0012149 5197.459
## a[13]    86.838805 4.901824 78.94315 94.70806 1.0022252 5415.049
## a[14]    74.588776 4.892254 66.70769 82.28155 1.0061419 6201.765
## a[15]    76.358485 4.765478 68.61011 83.95755 1.0005471 5617.096
## a[16]    34.911261 4.807355 27.39249 42.81919 1.0034562 4996.251
## a[17]    84.690792 4.797903 77.15588 92.52530 1.0019987 5432.365
## a[18]    65.074728 4.886075 57.18416 72.69642 1.0045333 6606.349
## a[19]    63.231107 4.793002 55.48346 70.90928 1.0037856 5676.571
## a[20]    79.697001 4.866240 71.94790 87.56718 1.0035538 5967.776
## a[21]    30.369812 4.899518 22.55073 38.13108 1.0009967 5253.893
## a[22]    62.709968 4.725827 55.22957 70.23577 1.0003572 7404.072
## a[23]    67.427985 4.788840 59.76362 75.10686 1.0029133 5351.814
## a[24]    81.535150 4.741940 73.95096 89.03032 1.0017427 5464.543
## a[25]    55.010214 4.840785 47.42953 62.96822 1.0049586 6085.220
## a[26]    67.434436 4.739068 59.96062 74.95876 1.0021159 6164.406
## a[27]    75.649054 4.913257 67.74207 83.54998 1.0010128 6362.574
## a[28]    81.488379 4.660635 73.92604 88.92539 0.9999582 6327.554
## a[29]    46.253649 4.810893 38.57074 53.79868 1.0049045 5672.224
## a[30]    61.260278 4.673822 53.65320 68.70247 1.0013432 5690.895
## a[31]    23.469053 5.114613 15.36816 31.57722 1.0007722 5354.087
## a[32]    74.082006 4.840605 66.29799 81.77599 1.0009402 5886.113
## a[33]    70.626826 4.823152 62.81915 78.29396 1.0015286 5832.028
## a[34]    76.462800 4.843277 68.56998 84.02210 1.0025194 6883.911
## a[35]    75.572553 4.717920 68.09133 83.12755 1.0058299 5293.603
## a[36]    69.197828 4.764084 61.55910 76.99101 1.0024002 6139.124
## a[37]    49.518817 4.700441 41.98837 57.09118 1.0010456 4710.058
## a[38]    73.710164 4.932679 65.69411 81.61300 1.0028124 6378.396
## a[39]    72.772866 4.783717 65.00724 80.30890 1.0055246 6250.379
## a[40]    45.785394 4.846582 38.04010 53.37593 1.0015821 6324.488
## a[41]    73.738559 4.887535 65.93367 81.72445 1.0012916 6199.265
## a[42]    26.216631 5.083953 18.26280 34.61207 1.0030459 5052.563
## a[43]    33.121094 4.850825 25.59334 40.87299 1.0010879 5411.410
## a[44]    74.198091 4.682154 66.69696 81.59399 1.0070692 6485.594
## a[45]    76.973015 4.874692 69.15629 84.69509 1.0010603 5720.713
## a[46]    73.689479 4.849046 65.80651 81.37046 1.0026245 4437.984
## a[47]    55.951497 4.749996 48.36908 63.62176 1.0014202 5516.828
## a[48]    69.715662 4.820367 62.00446 77.43062 1.0025555 5772.378
## a[49]    72.362550 4.812730 64.57572 80.00205 0.9998971 5552.498
## a[50]    72.711909 4.930061 64.73394 80.64126 1.0012210 5531.604
## mu_a     65.586927 2.418753 61.82518 69.51800 1.0019391 5120.128
## sigma_ID 16.568114 1.591735 13.99826 19.14733 1.0027477 3039.192
## sigma     7.077867 0.730829  6.00359  8.31929 1.0035903 1612.349
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{post }\OtherTok{\textless{}{-}} \FunctionTok{extract.samples}\NormalTok{(m5}\FloatTok{.1}\NormalTok{)}
\NormalTok{var\_patients }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{sigma\_ID}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)  }\CommentTok{\# Between{-}patient variance}
\NormalTok{var\_residual }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{sigma}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)     }\CommentTok{\# Residual variance}
\NormalTok{var\_patients }\SpecialCharTok{/}\NormalTok{ (var\_patients }\SpecialCharTok{+}\NormalTok{ var\_residual) }\CommentTok{\# ICC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8454822
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0.846}
\CommentTok{\# not too bad; very close to the result from the irr package}
\end{Highlighting}
\end{Shaded}

In the output from \texttt{precis(m5.1,\ depth\ =\ 2)} above we see

\begin{itemize}
\tightlist
\item
  all 50 intercept estimates for each patient: \texttt{a{[}ID{]}}
\item
  \texttt{mu\_a}is the overall intercept.
\item
  \texttt{sigma\_ID} is the \textbf{patient variability}.
\item
  \texttt{sigma} is the \textbf{residual variability}.
\end{itemize}

We have just squared the sigmas to get the variances.

Remember: In the background of all ICCs, there is always a statistical model to predict
the outcome. Depending on the predictors, we get different models and
probably different ICCs.

Let's jump back into the Frequentist world and see if we can get the same result.

We can also estimate a \textbf{random intercept model} with the \texttt{lme4} package using
the command \texttt{lmer}in the Frequentist framework. No priors:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lme4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'Matrix'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:tidyr':
## 
##     expand, pack, unpack
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m5}\FloatTok{.2} \OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(ROM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{ID), }\AttributeTok{data =}\NormalTok{ df\_long)}
\FunctionTok{summary}\NormalTok{(m5}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed model fit by REML ['lmerMod']
## Formula: ROM ~ (1 | ID)
##    Data: df_long
## 
## REML criterion at convergence: 791
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.91875 -0.44821  0.00964  0.51325  1.47941 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  ID       (Intercept) 270.99   16.462  
##  Residual              47.35    6.881  
## Number of obs: 100, groups:  ID, 50
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   65.590      2.428   27.02
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{VarCorr}\NormalTok{(m5}\FloatTok{.2}\NormalTok{), }\AttributeTok{comp =} \StringTok{"Variance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Groups   Name        Variance
##  ID       (Intercept) 270.99  
##  Residual              47.35
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ICC = }
\FloatTok{270.99} \SpecialCharTok{/}\NormalTok{ (}\FloatTok{270.99} \SpecialCharTok{+} \FloatTok{47.35}\NormalTok{) }\CommentTok{\# }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8512597
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0.8512597}
\CommentTok{\# {-}\textgreater{} exactly the same result as the irr package}
\end{Highlighting}
\end{Shaded}

The expression \texttt{Formula:\ ROM\ \textasciitilde{}\ (1\ \textbar{}\ ID)} specifies that we want to fit a model with
a random intercept. This means that every patient (ID) gets its own intercept
which is drawn from a normal distribution.

So far, we have only looked at the general \textbf{\(ICC\)} (ICC1 in the \texttt{psych}output)
(see also page 106 in the book).

There, we have not yet explicitely considered a bias (=systematic difference
between the raters) that the raters could have. In the book,
they introduce a bias of 5 degrees (Mary measures 5 degrees more than Peter on average).

The \textbf{model für ICC 2 and 3} in the \texttt{psych} output explicitely considers this
(systematic) difference that could occur between the raters.
This results in an extra term in the denominator
of the ICC, an additional variance component.

From the \textbf{same statistical model} (!) we take the variance components to calculate:

\[ICC_{agreement} = \frac{\sigma_{\alpha}^2}{\sigma_{\alpha}^2 + \mathbf{\sigma_{rater}^2} + \sigma_{\varepsilon}^2}\]

where \(\sigma_{rater}^2\) is the variance due to systematic rater differences.

\[ICC_{consistency} = \frac{\sigma_{\alpha}^2}{\sigma_{\alpha}^2 + \sigma_{\varepsilon}^2}\]

\textbf{We will now introduce the 5 degree bias} and use our Bayesian
framework to estimate the ICC.
By introducing a bias, we should see
a lower ICC. Note, that the prediction quality of Mary's scores
given Peter's scores should not change, since we would only shift Mary's scores
down by 5 degrees, which would not disturb the linear regression model. We can
always shift the points to where we want them to be. We do that for instance
when we scale or standardize the data.

Admitted, the Bayesian version in this case takes longer and is more complex.
The advantage is still that it's fully probabilistic and one could work with
detailed prior information, especially for smaller smaple sizes.

Anyhow, let's try to give the model equations considering
the introduced bias. This is the model \textbf{for both}
\(ICC_{agreement}\) and \(ICC_{consistency}\)!

\[
\begin{array}{rcl}
ROM_i &\sim& N(\mu_i, \sigma_{\varepsilon}) \\
\mu_i &=& \alpha[ID] + \beta[Rater] \\
\alpha[ID] &\sim& \text{Normal}(\mu_{\alpha}, \sigma_{\alpha}) \\
\beta[Rater] &\sim& \text{Normal}(0, \sigma_{\beta}) \\
\mu_{\alpha} &\sim& \text{Normal}(66, 20) \\
\sigma_{\alpha} &\sim& \text{Exp}(0.5) \\
\sigma_{\beta} &\sim& \text{Exp}(1) \\
\sigma_{\varepsilon} &\sim& \text{Exp}(1)
\end{array}
\]

As you can see, \(\mu_i\) now consists of the patient-specific intercept \(\alpha[ID]\)
(everyone of the 50 patients gets one)
and the rater-specific effect \(\beta[Rater]\) (Mary and Peter get one).
So, in total, we have \textbf{three sources of variability}:

\begin{itemize}
\tightlist
\item
  the patient variability \(\sigma_{\alpha}\),
\item
  the rater variability \(\sigma_{\beta}\),
\item
  and the residual variability \(\sigma_{\varepsilon}\).
\end{itemize}

Note, that if Peter measures each of the 50 patients twice,
the systematic difference between Peter's measurements would
be zero. Of course, one could be creative and think of
a learning effect or something.

Draw the model structure as \hyperref[exercise5]{exercise 5}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rethinking)}
\FunctionTok{library}\NormalTok{(conflicted)}
\FunctionTok{conflicts\_prefer}\NormalTok{(posterior}\SpecialCharTok{::}\NormalTok{sd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [conflicted] Will prefer posterior::sd over any other package.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_long\_bias }\OtherTok{\textless{}{-}}\NormalTok{ df\_long }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{ROM =}\NormalTok{ ROM }\SpecialCharTok{+} \FunctionTok{ifelse}\NormalTok{(Rater }\SpecialCharTok{==} \StringTok{"ROMas.Mary"}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\FunctionTok{head}\NormalTok{(df\_long\_bias)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 3
##      ID Rater         ROM
##   <int> <fct>       <dbl>
## 1     1 ROMas.Peter    66
## 2     1 ROMas.Mary     75
## 3     2 ROMas.Peter    65
## 4     2 ROMas.Mary     68
## 5     3 ROMas.Peter    96
## 6     3 ROMas.Mary     87
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{m5}\FloatTok{.2} \OtherTok{\textless{}{-}} \FunctionTok{ulam}\NormalTok{(}
  \FunctionTok{alist}\NormalTok{(}
    \CommentTok{\# Likelihood}
\NormalTok{    ROM }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(mu, sigma\_eps),}
    
    \CommentTok{\# Model for mean ROM with patient and rater effects}
\NormalTok{    mu }\OtherTok{\textless{}{-}}\NormalTok{ alpha[ID] }\SpecialCharTok{+}\NormalTok{ beta[Rater],}
    
    \CommentTok{\# Patient{-}specific random effects}
\NormalTok{    alpha[ID] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(mu\_alpha, sigma\_alpha),}
    
    \CommentTok{\# Rater effect (Peter/Mary)}
\NormalTok{    beta[Rater] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(}\DecValTok{0}\NormalTok{, sigma\_beta),}
    
    \CommentTok{\# Priors for hyperparameters}
\NormalTok{    mu\_alpha }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(}\DecValTok{66}\NormalTok{, }\DecValTok{10}\NormalTok{),  }\CommentTok{\# Population mean ROM}
\NormalTok{    sigma\_alpha }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dexp}\NormalTok{(}\FloatTok{0.5}\NormalTok{),  }\CommentTok{\# Between{-}patient SD (less aggressive shrinkage)}
\NormalTok{    sigma\_beta }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dexp}\NormalTok{(}\DecValTok{1}\NormalTok{),   }\CommentTok{\# Rater SD (better regularization)}
\NormalTok{    sigma\_eps }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dexp}\NormalTok{(}\DecValTok{1}\NormalTok{)     }\CommentTok{\# Residual SD (prevents over{-}shrinkage)}
\NormalTok{  ), }
  \AttributeTok{data =}\NormalTok{ df\_long\_bias, }
  \AttributeTok{chains =} \DecValTok{8}\NormalTok{, }\AttributeTok{cores =} \DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Running MCMC with 8 chains, at most 4 in parallel, with 1 thread(s) per chain...
## 
## Chain 1 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 2 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 3 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 3 Iteration: 100 / 1000 [ 10%]  (Warmup)
\end{verbatim}

\begin{verbatim}
## Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
## Chain 3 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d49a8d92c.stan', line 21, column 4 to column 45)
## Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
## Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
## Chain 3
\end{verbatim}

\begin{verbatim}
## Chain 4 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 1 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 1 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 1 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 1 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 1 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 1 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 1 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 1 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 1 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 1 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 2 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 2 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 2 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 2 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 2 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 2 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 2 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 2 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 2 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 2 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 2 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 3 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 3 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 3 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 3 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 3 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 3 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 3 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 3 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 3 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 3 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 4 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 4 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 4 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 4 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 4 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 4 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 4 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 2 finished in 0.2 seconds.
## Chain 3 finished in 0.2 seconds.
## Chain 1 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 4 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 4 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 4 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 4 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 5 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 5 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 5 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 6 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 1 finished in 0.3 seconds.
## Chain 4 finished in 0.3 seconds.
## Chain 5 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 5 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 5 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 5 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 5 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 5 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 5 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 5 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 5 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 6 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 6 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 6 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 6 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 6 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 6 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 6 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 6 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 6 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 6 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 6 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 7 Iteration:   1 / 1000 [  0%]  (Warmup) 
## Chain 7 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 8 Iteration:   1 / 1000 [  0%]  (Warmup)
\end{verbatim}

\begin{verbatim}
## Chain 8 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
## Chain 8 Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in '/var/folders/pm/jd6n6gj10371_bml1gh8sc5w0000gn/T/RtmpHkdESG/model-1465d49a8d92c.stan', line 21, column 4 to column 45)
## Chain 8 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
## Chain 8 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
## Chain 8
\end{verbatim}

\begin{verbatim}
## Chain 5 finished in 0.2 seconds.
## Chain 6 finished in 0.2 seconds.
## Chain 7 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 7 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 7 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 7 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 7 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 7 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 7 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 7 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 7 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 8 Iteration: 100 / 1000 [ 10%]  (Warmup) 
## Chain 8 Iteration: 200 / 1000 [ 20%]  (Warmup) 
## Chain 8 Iteration: 300 / 1000 [ 30%]  (Warmup) 
## Chain 8 Iteration: 400 / 1000 [ 40%]  (Warmup) 
## Chain 8 Iteration: 500 / 1000 [ 50%]  (Warmup) 
## Chain 8 Iteration: 501 / 1000 [ 50%]  (Sampling) 
## Chain 8 Iteration: 600 / 1000 [ 60%]  (Sampling) 
## Chain 8 Iteration: 700 / 1000 [ 70%]  (Sampling) 
## Chain 7 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 8 Iteration: 800 / 1000 [ 80%]  (Sampling) 
## Chain 8 Iteration: 900 / 1000 [ 90%]  (Sampling) 
## Chain 8 Iteration: 1000 / 1000 [100%]  (Sampling) 
## Chain 7 finished in 0.2 seconds.
## Chain 8 finished in 0.3 seconds.
## 
## All 8 chains finished successfully.
## Mean chain execution time: 0.2 seconds.
## Total execution time: 0.8 seconds.
\end{verbatim}

\begin{verbatim}
## Warning: 32 of 4000 (1.0%) transitions ended with a divergence.
## See https://mc-stan.org/misc/warnings for details.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{precis}\NormalTok{(m5}\FloatTok{.2}\NormalTok{, }\AttributeTok{depth =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  mean        sd       5.5%      94.5%     rhat ess_bulk
## alpha[1]    70.098372 4.7042991 62.6322845 77.6520050 1.001530 4043.560
## alpha[2]    66.569489 4.7693775 59.0935945 74.1363355 1.001763 3908.733
## alpha[3]    89.457889 4.6266261 82.0659185 96.5845055 1.001296 3557.326
## alpha[4]    78.863009 4.6795836 71.4526810 86.5071480 1.001155 3872.797
## alpha[5]    61.160273 4.8743939 53.3981645 68.9984655 1.005173 4221.798
## alpha[6]    71.570030 4.7791323 63.7869920 79.2358775 1.001868 4220.747
## alpha[7]    72.059336 4.7721724 64.4189790 79.7012990 1.000718 3938.921
## alpha[8]    69.792439 4.7315623 62.3561175 77.4358765 1.004061 4836.922
## alpha[9]    73.320955 4.6129611 65.7833975 80.7233240 1.002518 4349.003
## alpha[10]   83.397924 4.7182611 75.7780945 91.0030155 1.003485 4263.796
## alpha[11]   72.852797 4.5797786 65.5314130 80.2417660 1.001249 4967.112
## alpha[12]   44.784018 4.9074767 37.0184000 52.6481990 1.001981 5105.934
## alpha[13]   89.297771 4.7002217 81.6948340 96.7268745 1.002795 4083.770
## alpha[14]   77.059998 4.8425231 69.3173470 84.8155935 1.002627 3369.333
## alpha[15]   78.775251 4.6338086 71.4220010 86.1287545 1.002519 4491.709
## alpha[16]   37.435443 4.7659227 29.9392865 45.1209270 1.001814 3856.455
## alpha[17]   86.933759 4.7616634 79.3303120 94.4104210 1.002306 3681.805
## alpha[18]   67.437836 4.7736061 59.9265010 75.1330260 1.004932 4445.400
## alpha[19]   65.725657 4.7193609 58.3514780 73.2018035 1.000595 3350.151
## alpha[20]   82.091286 4.8009036 74.3103950 89.6811220 1.004743 4093.597
## alpha[21]   32.817934 4.7967889 25.1070865 40.5885315 1.000936 3666.192
## alpha[22]   65.211938 4.7906230 57.7547720 72.7764005 1.000964 4475.820
## alpha[23]   69.718651 4.7591161 62.0347805 77.2424650 1.003816 4337.102
## alpha[24]   83.907862 4.6610319 76.3731975 91.1301860 1.002046 3808.518
## alpha[25]   57.451790 4.7134912 49.8447075 64.9600665 1.001046 3569.522
## alpha[26]   69.738023 4.7361684 62.1954645 77.3361665 1.001038 4163.223
## alpha[27]   77.935815 4.5854233 70.6915745 85.0976475 1.002237 3059.448
## alpha[28]   83.948403 4.7068664 76.4390250 91.4390530 1.004254 3594.525
## alpha[29]   48.762531 4.6822810 41.3137875 56.2599180 1.003356 3548.471
## alpha[30]   63.821278 4.6746985 56.3676810 71.4452815 1.001947 3289.059
## alpha[31]   26.016448 4.8900457 18.4122570 33.9521325 1.002461 3510.190
## alpha[32]   76.507025 4.7626648 68.8128075 84.1518680 1.001263 3860.511
## alpha[33]   72.904999 4.8802530 65.1628015 80.7713440 1.004172 4655.722
## alpha[34]   78.781812 4.7523672 71.0831555 86.5075635 1.000770 4146.453
## alpha[35]   77.862658 4.7946130 70.3506130 85.5765545 1.001998 4465.411
## alpha[36]   71.573811 4.8000164 63.9453735 79.2936730 1.001894 4075.348
## alpha[37]   51.967007 4.6390314 44.5768340 59.4492165 1.003622 3052.391
## alpha[38]   76.216932 4.6867388 68.6011415 83.5097200 1.000684 4009.291
## alpha[39]   75.186970 4.7760475 67.6954900 82.7756935 1.000853 4225.980
## alpha[40]   48.313854 4.7909876 40.7513665 55.8724120 1.006659 3989.731
## alpha[41]   76.106722 4.9004359 68.2118730 83.8790650 1.006167 3959.068
## alpha[42]   28.860624 4.7804416 21.0606160 36.4982260 1.000772 3845.006
## alpha[43]   35.551375 4.7650211 28.0875875 43.2557090 1.003077 3645.726
## alpha[44]   76.591764 4.7437801 69.2447800 84.3623410 1.002210 3825.927
## alpha[45]   79.246903 4.7335075 71.5678685 86.8304860 1.002345 3067.135
## alpha[46]   76.098305 4.6831257 68.8458735 83.4560000 1.002134 3819.541
## alpha[47]   58.340678 4.5995812 51.1278315 65.6481140 1.004645 3747.535
## alpha[48]   71.968853 4.6893025 64.4579350 79.4666705 1.002250 3229.449
## alpha[49]   74.723807 4.6761841 67.3960390 82.2802220 1.005403 4461.720
## alpha[50]   75.176016 4.7992669 67.7644245 82.8261675 1.003107 4355.544
## beta[1]      1.299615 1.5127533 -0.6688352  3.9638292 1.010280 1068.607
## beta[2]     -1.167443 1.4935396 -3.7346674  0.8214701 1.007193 1080.743
## mu_alpha    67.876858 2.5564075 63.8479340 71.9241770 1.005497 1898.765
## sigma_alpha 15.393556 1.5603445 13.0410405 17.9750610 1.000238 4190.714
## sigma_beta   1.679613 1.0172190  0.4076696  3.4572703 1.004039 1704.538
## sigma_eps    6.733778 0.6484083  5.7829221  7.8311868 1.003769 2009.472
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{precis}\NormalTok{(m5}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 52 vector or matrix parameters hidden. Use depth=2 to show them.
\end{verbatim}

\begin{verbatim}
##                  mean        sd       5.5%     94.5%     rhat ess_bulk
## mu_alpha    67.876858 2.5564075 63.8479340 71.924177 1.005497 1898.765
## sigma_alpha 15.393556 1.5603445 13.0410405 17.975061 1.000238 4190.714
## sigma_beta   1.679613 1.0172190  0.4076696  3.457270 1.004039 1704.538
## sigma_eps    6.733778 0.6484083  5.7829221  7.831187 1.003769 2009.472
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# check systematic difference for rater in posterior}
\NormalTok{post }\OtherTok{\textless{}{-}} \FunctionTok{extract.samples}\NormalTok{(m5}\FloatTok{.2}\NormalTok{)}
\FunctionTok{mean}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{beta[,}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ post}\SpecialCharTok{$}\NormalTok{beta[,}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.467058
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ICC agreement:}
\NormalTok{post }\OtherTok{\textless{}{-}} \FunctionTok{extract.samples}\NormalTok{(m5}\FloatTok{.2}\NormalTok{)}
\NormalTok{(var\_patients }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{sigma\_alpha}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))  }\CommentTok{\# Between{-}patient variance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 239.3956
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(var\_raters }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{sigma\_beta}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))     }\CommentTok{\# Rater variance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.855577
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(var\_residual }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{sigma\_eps}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))    }\CommentTok{\# Residual variance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 45.7641
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ICC\_agreement = }
\NormalTok{var\_patients }\SpecialCharTok{/}\NormalTok{ (var\_patients }\SpecialCharTok{+}\NormalTok{ var\_raters }\SpecialCharTok{+}\NormalTok{ var\_residual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8283147
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0.8033613 (sigma\_alpha \textasciitilde{} dexp(1))}
\CommentTok{\# 0.83 (sigma\_alpha \textasciitilde{} dexp(0.5))}

\CommentTok{\# ICC (Single\_fixed\_raters) = ICC3 in psych output = }
\NormalTok{var\_patients }\SpecialCharTok{/}\NormalTok{ (var\_patients }\SpecialCharTok{+}\NormalTok{ var\_residual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8395142
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0.8415256}
\end{Highlighting}
\end{Shaded}

It should be noted that this ICC is very sensitive to the choice of the prior.
If you choose too agressive priors for the standard deviations \(\sigma_{\alpha},
\sigma_{\beta}, \sigma_{\varepsilon}\), you will get a too low ICC.

I have played around a little with the parameters in the exponential priors
to get the desired result which compares nicely to the two alternative methods below:
using the \texttt{psych} package and with the \texttt{lmer}
package. Both use a Frequentist random intercept model in the background.
Using a package like \texttt{psych} gives a rather convenient interface to
elicit the ICC. It can never hurt to peek behind the curtain a little bit though.

\textbf{\texttt{psych} package} (Frequentist):

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(psych)}
\FunctionTok{library}\NormalTok{(conflicted)}
\CommentTok{\# needs wide format}
\CommentTok{\#conflicts\_prefer(dplyr::select)}
\NormalTok{df\_wide }\OtherTok{\textless{}{-}}\NormalTok{ df\_long\_bias }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ Rater, }\AttributeTok{values\_from =}\NormalTok{ ROM)}
\NormalTok{df\_wide\_values }\OtherTok{\textless{}{-}}\NormalTok{ df\_wide }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{ID)}
\NormalTok{psych}\SpecialCharTok{::}\FunctionTok{ICC}\NormalTok{(df\_wide\_values) }\CommentTok{\# ICC1 = 0.83}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call: psych::ICC(x = df_wide_values)
## 
## Intraclass correlation coefficients 
##                          type  ICC  F df1 df2       p lower bound upper bound
## Single_raters_absolute   ICC1 0.83 11  49  50 1.1e-14        0.72        0.90
## Single_random_raters     ICC2 0.83 12  49  49 1.4e-15        0.71        0.91
## Single_fixed_raters      ICC3 0.85 12  49  49 1.4e-15        0.75        0.91
## Average_raters_absolute ICC1k 0.91 11  49  50 1.1e-14        0.84        0.95
## Average_random_raters   ICC2k 0.91 12  49  49 1.4e-15        0.83        0.95
## Average_fixed_raters    ICC3k 0.92 12  49  49 1.4e-15        0.86        0.95
## 
##  Number of subjects = 50     Number of Judges =  2
## See the help file for a discussion of the other 4 McGraw and Wong estimates,
\end{verbatim}

\textbf{\texttt{lmer} package}:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# \_lmer{-}{-}{-}{-}{-}{-}}
\NormalTok{m5}\FloatTok{.3} \OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(ROM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ ID) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ Rater), }\AttributeTok{data =}\NormalTok{ df\_long\_bias)}
\FunctionTok{summary}\NormalTok{(m5}\FloatTok{.3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed model fit by REML ['lmerMod']
## Formula: ROM ~ (1 | ID) + (1 | Rater)
##    Data: df_long_bias
## 
## REML criterion at convergence: 793.2
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.87448 -0.46270  0.00272  0.57820  1.45008 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  ID       (Intercept) 270.882  16.458  
##  Rater    (Intercept)   6.193   2.489  
##  Residual              47.557   6.896  
## Number of obs: 100, groups:  ID, 50; Rater, 2
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   68.090      2.998   22.71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{VarCorr}\NormalTok{(m5}\FloatTok{.3}\NormalTok{), }\AttributeTok{comp =} \StringTok{"Variance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Groups   Name        Variance
##  ID       (Intercept) 270.882 
##  Rater    (Intercept)   6.193 
##  Residual              47.557
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Groups   Name        Variance}
\CommentTok{\# ID       (Intercept) 270.882 }
\CommentTok{\# Rater    (Intercept)   6.193 }
\CommentTok{\# Residual              47.557 }


\CommentTok{\# ICC (Single\_random\_raters) = ICC2 in psych output}
\FloatTok{270.882} \SpecialCharTok{/}\NormalTok{ (}\FloatTok{270.882} \SpecialCharTok{+} \FloatTok{6.193} \SpecialCharTok{+} \FloatTok{47.557}\NormalTok{) }\CommentTok{\# }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8344279
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0.8344279}

\CommentTok{\# ICC (Single\_fixed\_raters) = ICC3 in psych output}
\FloatTok{270.882} \SpecialCharTok{/}\NormalTok{ (}\FloatTok{270.882} \SpecialCharTok{+} \FloatTok{47.557}\NormalTok{) }\CommentTok{\#}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8506559
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0.85}
\end{Highlighting}
\end{Shaded}

There are basically \textbf{two different random effects}:

\begin{itemize}
\item
  \textbf{Nested random effects}: The patients (respectively their \(ROMs\)) would cluster within the raters.
  This would mean, a patient would only be measured by Peter twice or by Mary twice.
  In that case, the \(ROMs\) would cluster within the patients (because of the repeated measurement)
  and all patients measured by (for instance) Mary would cluster together (and be potentially more similar).
  In our case at hand all patients are measured by Peter and Mary, so we do not have nested random effects.
  In \texttt{lmer} nested effects would be specified as \texttt{ROM\ \textasciitilde{}\ (1\textbar{}Rater/ID)}.
\item
  \textbf{Crossed random effects}:
  Not nested.
  In R this would be specified as

  \texttt{ROM\ \textasciitilde{}\ (1\textbar{}ID)\ +\ (1\textbar{}Rater)}.
\end{itemize}

\subsubsection{\texorpdfstring{Explanation of ICCs in the \texttt{psych} output}{Explanation of ICCs in the psych output}}\label{explanation-of-iccs-in-the-psych-output}

If you want to know all the details, refer to \href{https://d1wqtxts1xzle7.cloudfront.net/50483847/syarat_reliabilitas_icc-libre.pdf?1479841049=&response-content-disposition=inline\%3B+filename\%3DIntraclass_Correlations_Uses_in_Assessin.pdf&Expires=1740684631&Signature=hHiFbcQD3PDVIyWDJ-bUhcm3WtsK19YhHm6FKtnafNdqsm9NhR6cr9lbCf~gVV5SYG1XlTwLlcfJkQ9Z-ahjmmNV893aWi5plo~yL4oZBEjrmFa9WCd7k6vzFTkri1Xbgfh~GyPARWXBtqABytovtL-RD1420Kw9qk150nw3-kUWcuvRiIc~r0y65XQaXf-V9mm~uXRFdUqec4Vs-Bwh~IrJfHWQASGgp8wZjzh2130MCP3-iaorxNn~79c~nm2f1aIl5WRqRXB6EIy8HlrNFpxNSt1pgTPZoZadEECM4qH395KLY5ijUnhoCDT9AmcOplPnFiC5t8dKW-n25ziofQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA}{Shrout and Fleiss (1979)}.
The help-function \texttt{?psych::ICC} contains a relatively good and much shorter explanation.
The variance formulae given in the help-file are probably somewhat confusing.
We try to stick to the notation of the book.

Let's talk about the first three \textbf{ICCs in the \texttt{psych} output}:

\begin{itemize}
\item
  \textbf{Single\_raters\_absolute ICC1:}
  According to the help file: ``Each target {[}i.e.~patient{]} is rated by a different
  judge {[}i.e.~rater{]} and the judges are selected at random.'' So, variability due to raters
  is implied and cannot be disentangled.
  This is formally not our situation, since we have only two raters and
  50 patients. But for this case, we do not care who measures, since we do not
  model it, hence, we cannot know if there are systematic differences between
  the raters. There might as well be 50 raters doing their thing, or just 2 as in our case.
  This is the ICC we have calculated above; the overall ICC
  in the book and it is based on the following model:

  \[Y_{ij} = \eta_i + \varepsilon_i\]
  where \(i \in {1,...,50}\) is the \emph{patient} and \(j \in {1,2}\) is the \emph{measurement}
  (\(=50*2=100\) rows in long format).
  Note that we do not mention a rater here, since we do not care who took the
  measurement. It is not part of the model. The ICC is then calculated as:

  \[ICC = \frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 + \sigma_{\varepsilon}^2}\]

  whereas we could get the variance components from either the posterior in the Bayesian
  setting or from the \texttt{lmer} output in the Frequentist setting.
\item
  \textbf{Single\_random\_raters ICC2:}
  ICC2 (\(=ICC_{agreement}\) in the book) and ICC3 (\(=ICC_{consistency}\) in the book)
  are based on the \textbf{same (!)} statistical model. The only difference is
  that ICC2 assumes that the (in our case) 2 raters are randomly selected from a larger pool of raters,
  hence, the rater variability must be explicitely considered and yields a potentially smaller
  value for the ICC. Compared to ICC1, we have repeated measurements from the same raters
  in 50 patients. That's why we can model their bias. One observation would not be enough.
  The help file says: ``A random sample of k judges rate each target.
  The measure is one of absolute agreement in the ratings.''
  A random sample of k (2 in our case) judges means that we cannot rule out the variability
  due to raters (you get a variety of them and their biases are different).

  \[Y_{ij} = \eta_i + \beta_j + \varepsilon_i\]
  where \(i \in {1,...,50}\) is the \emph{patient}, \(j \in {1,2}\) is the \textbf{rater}
  (doing one measurement in each patient). The ICC is then calculated as:

  \[ICC_{agreement} = \frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 +\mathbf{\sigma_{rater}^2} + \sigma_{\varepsilon}^2}\]
\item
  \textbf{Single\_fixed\_raters ICC3:}
  ICC3 (\(=ICC_{consistency}\) in the book) is based on the \textbf{same model as ICC2},
  but assumes that the raters are fixed.
  This means that \textbf{the raters are the same for all patients} in the future study.
  So, we have considered the rater variability in the model
  (which was possible due to the repeated measurements from the same raters in 50 patients),
  but do not care since Mary and Peter will be the people doing the future
  measurements, not other therapists. If you fix a random variable
  (\emph{raters} in this case), variance is zero. The help file says:
  ``A fixed set of k judges rate each target.
  There is no generalization to a larger population of judges.''
  The ICC is then calculated as:

  \[ICC_{consistency} = \frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 + \sigma_{\varepsilon}^2}\]

  \textbf{Important}: ICC1 and ICC3 are \textbf{not} identical, since ICC1 does not consider the rater variability
  in the model. They are based on \emph{different} statistical models.
  ICC2 and ICC3 are based on the \emph{same} model.
\end{itemize}

If there is no systematic difference between raters, all 3 ICCs and the Pearson
correlation (r) are the same (see Figure 5.3 in the book).

\(ICC_{consistency}\) vs.~\(ICC_{agreement}\):
The latter is used, when we need Peter and Mary to concur in their measurements.
Patients coming to Peters practice will get the same (or very similar) ``diagnosis'' (ROM-value)
from Mary. When there is systematic difference (line is shifted downwards in Figure 5.3),
this cannot be guaranteed.
If we only need Peter and Mary to \emph{rank} the patients in the same order,
we can use \(ICC_{consistency}\).

\begin{itemize}
\item
  \textbf{Average\_raters\_absolute ICC1k:}
  According to the help file ``ICC1k, ICC2k, ICC3k reflect the means of k raters.''
  In general, if you take the mean, you get an estimate with lower variance (central limit theorem).
  In the book on page 109, we find the derivation of the ICC for the average of k raters.
  We do not need a new statistical model, although we take the sum (or equivalently, the mean) of the
  measurements of Peter and Mary, which seems a bit unintuitive at first.

  If we go back to \hyperref[ICC]{the definition of the ICC above}, it follows that:

  \[Y_{1} + Y_{2} = 2 \eta + \varepsilon_1 + \varepsilon_2\]
  for the same person with true \(\eta\). Since ther errors \(\varepsilon_i\) are
  independent and the true score \(\eta\) is also independent from the errors,
  it follows that:

  \[\mathbb{Var}(Y_1 + Y_2) = \mathbb{Var}(2 \eta + \varepsilon_1 + \varepsilon_2)=\]
  \[ \mathbb{Var}(2 \eta) + \mathbb{Var}(\varepsilon_1 + \varepsilon_2)=\]
  \[4 \mathbb{Var}(\eta) + 2 \mathbb{Var}(\varepsilon)=\]

  If we divide by 4, we get:
  \[\frac{1}{4}\mathbb{Var}(Y_1 + Y_2) = \mathbb{Var}(\frac{Y_1 + Y_2}{2}) = 
  \mathbb{Var}(\eta) + \frac{\mathbb{Var}(\varepsilon)}{2} = 
  \sigma_{\eta}^2 + \frac{\sigma_{\varepsilon}^2}{2}\]

  Hence, the ICC for the average of 2 raters is (\(k=2\)):

  \[ICC1k = \frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 + \frac{\sigma_{\varepsilon}^2}{2}}\]

  Again, the model does not care about the raters, it just knows that there are
  two measurements. A potential bias between raters is not considered.

  It is also interesting to note that we do not fit a new model to get the ICC1k.
  We could not compare the first average (of 2 measurements) to the second average
  (of 2 measurements), since we only have 2 measurements per patient.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(ROM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{ID), }\AttributeTok{data =}\NormalTok{ df\_long\_bias)}
\FunctionTok{summary}\NormalTok{(m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed model fit by REML ['lmerMod']
## Formula: ROM ~ (1 | ID)
##    Data: df_long_bias
## 
## REML criterion at convergence: 797.3
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.02334 -0.52483 -0.03788  0.57830  1.59879 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  ID       (Intercept) 267.79   16.364  
##  Residual              53.75    7.331  
## Number of obs: 100, groups:  ID, 50
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   68.090      2.428   28.05
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{VarCorr}\NormalTok{(m), }\AttributeTok{comp =} \StringTok{"Variance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Groups   Name        Variance
##  ID       (Intercept) 267.79  
##  Residual              53.75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ICC1k = }
\FloatTok{267.79} \SpecialCharTok{/}\NormalTok{ (}\FloatTok{267.79} \SpecialCharTok{+} \FloatTok{53.75}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9087947
\end{verbatim}

This is identical to the ICC1k in the \texttt{psych} output.

ICC1k would approach \(1\) if \(k\) goes to infinity.
\textbf{This makes sense}, since the \emph{true} measurement is \emph{defined} as the average of
infinite measurements (of either infinitely many different raters or infinitely many
measurements from the same rater).
Also it makes intuitive sense, that
reliability increases or equivalently the unexplained variance decreases
since we draw repeatedly from the same distribution (\(\eta\) and an error term \(\varepsilon\))
and the central limit theorem guarantees that we can estimate \(\eta\) as precicely
as we want (variance of the mean goes to zero) if we only draw often enough.

\begin{itemize}
\tightlist
\item
  \textbf{Average\_raters\_random ICC2/3k:}
  ICC2k and ICC3k are based on the same model as ICC2 and ICC3, respectively.
  We just need to divide the respective residual variance by \(k\) (in our case 2) to get
  the ICC for the average of \(k\) raters.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m5}\FloatTok{.3} \OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(ROM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ ID) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ Rater), }\AttributeTok{data =}\NormalTok{ df\_long\_bias)}
\FunctionTok{summary}\NormalTok{(m5}\FloatTok{.3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed model fit by REML ['lmerMod']
## Formula: ROM ~ (1 | ID) + (1 | Rater)
##    Data: df_long_bias
## 
## REML criterion at convergence: 793.2
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.87448 -0.46270  0.00272  0.57820  1.45008 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  ID       (Intercept) 270.882  16.458  
##  Rater    (Intercept)   6.193   2.489  
##  Residual              47.557   6.896  
## Number of obs: 100, groups:  ID, 50; Rater, 2
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   68.090      2.998   22.71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{VarCorr}\NormalTok{(m5}\FloatTok{.3}\NormalTok{), }\AttributeTok{comp =} \StringTok{"Variance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Groups   Name        Variance
##  ID       (Intercept) 270.882 
##  Rater    (Intercept)   6.193 
##  Residual              47.557
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Groups   Name        Variance}
\CommentTok{\# ID       (Intercept) 270.882 }
\CommentTok{\# Rater    (Intercept)   6.193 }
\CommentTok{\# Residual              47.557 }

\CommentTok{\# ICC2k =}
\FloatTok{270.882} \SpecialCharTok{/}\NormalTok{ (}\FloatTok{270.882} \SpecialCharTok{+}\NormalTok{ (}\FloatTok{6.193} \SpecialCharTok{+} \FloatTok{47.557}\NormalTok{) }\SpecialCharTok{/} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9097418
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ICC3k =}
\FloatTok{270.882} \SpecialCharTok{/}\NormalTok{ (}\FloatTok{270.882} \SpecialCharTok{+} \FloatTok{47.557} \SpecialCharTok{/} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.919302
\end{verbatim}

These values are identical to the ICC2k and ICC3k in the \texttt{psych} output.

\subsubsection{Summary Peter and Mary, with and without bias (ICC1-3)}\label{summary-peter-and-mary-with-and-without-bias-icc1-3}

Below, we summarize the results for the ICCs (calculated with \texttt{psych})
for the unbiased and biased case (Mary measures on average 5 degrees more than peter).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(pacman)}
\FunctionTok{p\_load}\NormalTok{(conflicted, tidyverse, flextable)}

\CommentTok{\# Ensure select() from dplyr is used}
\CommentTok{\#conflicted::conflicts\_prefer("select", "dplyr")}

\CommentTok{\# Unbiased ICC Calculation}
\NormalTok{df\_wide\_unbiased }\OtherTok{\textless{}{-}}\NormalTok{ df\_long }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ Rater, }\AttributeTok{values\_from =}\NormalTok{ ROM)}
\NormalTok{df\_wide\_values\_unbiased }\OtherTok{\textless{}{-}}\NormalTok{ df\_wide\_unbiased }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{ID)}
\NormalTok{icc\_results\_unbiased }\OtherTok{\textless{}{-}}\NormalTok{ psych}\SpecialCharTok{::}\FunctionTok{ICC}\NormalTok{(df\_wide\_values\_unbiased)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## boundary (singular) fit: see help('isSingular')
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract relevant ICC values}
\NormalTok{icc\_unbiased\_df }\OtherTok{\textless{}{-}}\NormalTok{ icc\_results\_unbiased}\SpecialCharTok{$}\NormalTok{results }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(type, ICC) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Unbiased ICC}\StringTok{\textasciigrave{}} \OtherTok{=}\NormalTok{ ICC)}

\CommentTok{\# Biased ICC Calculation}
\NormalTok{df\_wide\_biased }\OtherTok{\textless{}{-}}\NormalTok{ df\_long\_bias }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ Rater, }\AttributeTok{values\_from =}\NormalTok{ ROM)}
\NormalTok{df\_wide\_values\_biased }\OtherTok{\textless{}{-}}\NormalTok{ df\_wide\_biased }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{ID)}
\NormalTok{icc\_results\_biased }\OtherTok{\textless{}{-}}\NormalTok{ psych}\SpecialCharTok{::}\FunctionTok{ICC}\NormalTok{(df\_wide\_values\_biased)}

\CommentTok{\# Extract relevant ICC values}
\NormalTok{icc\_biased\_df }\OtherTok{\textless{}{-}}\NormalTok{ icc\_results\_biased}\SpecialCharTok{$}\NormalTok{results }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(type, ICC) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{rename}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Biased ICC}\StringTok{\textasciigrave{}} \OtherTok{=}\NormalTok{ ICC)}

\NormalTok{icc\_merged\_df }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(icc\_unbiased\_df, }
\NormalTok{                           icc\_biased\_df, }
                           \AttributeTok{by =} \StringTok{"type"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{)}

\NormalTok{ft }\OtherTok{\textless{}{-}} \FunctionTok{flextable}\NormalTok{(icc\_merged\_df) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  flextable}\SpecialCharTok{::}\FunctionTok{set\_header\_labels}\NormalTok{(}\AttributeTok{type =} \StringTok{"ICC Type"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  flextable}\SpecialCharTok{::}\FunctionTok{set\_caption}\NormalTok{(}\StringTok{"Intraclass Correlation Coefficients {-} Unbiased vs. Biased"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  flextable}\SpecialCharTok{::}\FunctionTok{set\_table\_properties}\NormalTok{(}\AttributeTok{width =}\NormalTok{ .}\DecValTok{5}\NormalTok{, }\AttributeTok{layout =} \StringTok{"autofit"}\NormalTok{)}
\NormalTok{ft}
\end{Highlighting}
\end{Shaded}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{ccc}

\caption{Intraclass\ Correlation\ Coefficients\ -\ Unbiased\ vs.\ Biased}(\#tab:unnamed-chunk-11)\\

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{}l}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{ICC\ Type}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Unbiased\ ICC}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Biased\ ICC}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead \caption[]{Intraclass\ Correlation\ Coefficients\ -\ Unbiased\ vs.\ Biased}(\#tab:unnamed-chunk-11)\\

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{}l}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{ICC\ Type}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Unbiased\ ICC}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Biased\ ICC}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{}l}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{ICC1}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.8512574}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.8328336}}}} \\





\multicolumn{1}{>{}l}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{ICC2}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.8512574}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.8344281}}}} \\





\multicolumn{1}{>{}l}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{ICC3}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.8512574}}}} & \multicolumn{1}{>{}r}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.8506562}}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

The \textbf{left column} shows that the ICCs are identical for the \textbf{unbiased case}.
Specifically, ICC2 (=\(ICC_{agreement}\) in the book) and
ICC3 (\(ICC_{consistency}\) in the book) are based on the same model which explicitely
considers a potential bias between the raters. Since there is none,
the ICCs are the same.

In the \textbf{biased case} (right column), there \emph{is} a systematic difference between Mary and Peter -
5 degrees in our case.

\textbf{ICC1} does not care about it and shows a somewhat lower value compared to
before (\(0.833\)). The reason is because the agreement line (\(y=x\)) in a plot with
Mary on Y and Peter on X is shifted upwards by 5 degrees.
If you would introduce a bias of 15 degrees, the ICC would
be even lower (\(ICC1 = 0.61\), \(ICC2 = 0.65\), \hyperref[exercise1]{exercise 1}).
The unbiased column would of course stay the same.

\textbf{ICC2} now considers the bias of 5 degrees. The model knows about the shift.
If we compare the variance components of ICC1 and ICC2, we see:

\begin{verbatim}
## [1] "Model for ICC1: ROM ~ (1 | ID)"
\end{verbatim}

\begin{verbatim}
##  Groups   Name        Variance
##  ID       (Intercept) 267.79  
##  Residual              53.75
\end{verbatim}

\begin{verbatim}
## [1] "Model for ICC2 (and 3): ROM ~ (1 | ID) + (1 | Rater)"
\end{verbatim}

\begin{verbatim}
##  Groups   Name        Variance
##  ID       (Intercept) 270.882 
##  Rater    (Intercept)   6.193 
##  Residual              47.557
\end{verbatim}

The residual variance is smaller in the model with the rater effect.
The model explains the data better, since it knows about the bias (see \hyperref[excercise7]{exercise 7}).

Look at the \(\sigma_{\varepsilon}^2\) of the two models, they add up:

\[\sigma_{\varepsilon, ICC1}^2 = \sigma_{\varepsilon, ICC23}^2 + \sigma_{Rater}^2\]
\[53.75 = 47.557 + 6.193\]

Hence, we just split up the error differently by considering the bias.
The patient variability (\texttt{ID\ Variance} in the output) is slightly higher:
\(270.882\) compared to \(267.79\) before.
In the first model, patient variability was conflated with rater variation/systematic difference
because rater effects were not explicitely modeled. For this reason,
\texttt{ID\ Variance} increases slightly.
It is a rather small increase, so ICC1 and ICC2 are not that different.

For a bias of 15 degrees, the additivity of the variances remains.
The patient variability increases from \(223.89\) (ICC1) to \(270.882\) (ICC2),
hence the difference in ICCs is larger (\(ICC1=0.613\) vs.~\(ICC2=0.657\)).

\textbf{ICC3} considers the bias in the model but does not include it in the measurement
error since the raters are fixed.

\subsubsection{Difference between correlation and ICC}\label{difference-between-correlation-and-icc}

If we do not introduce a bias in the data, the correlation coefficient
is the same as the ICC (as seen above). On page 110, Figure 5.3, the authors show nicely
what the difference is between the correlation coefficient and the ICC.
It is also shown how \(ICC_{agreement}\) and \(ICC_{consistency}\) change with the bias.

\(ICC_{consistency}\) stays \(1\) if bias is introduced (assuming a hypothetical
perfect agreement before). Peter and Mary still \textbf{rank} the patients
in the same order.

Correlation \(r\) is always 1, no matter at what slope (\(\ne 0\)) the line is.
It measures the strength and direction of the \emph{linear} relationship between two variables.

\(ICC_{agreement}\) changes as soon as you depart from the 45 degree line
with respect to slope or
shift the line up or down (i.e., introduce a bias).

This is a good point in time to think for a moment about the type of measurement
for agreement with respect to \textbf{costs}. The ICC below weights each measurement
equally, although one larger outlier (large discrepancy between Peter and Mary)
may influence the ICC notably (\hyperref[exercise8]{exercise 8}).
One could possibly think of a situation where
overall agreement measure like the ICC is not adequate since,
for instance, exceeding a certain
difference threshold could decide between life and death.

\subsubsection{Bad news about the ICC?}\label{badnews}

Let's try to expand our intuitive understanding of what an ICC of 0.8 or so means.
For simplicity, we take the overall ICC, which is equal to the correlation coefficient,
if there is no bias present.

The following example demonstrates the meaning of the Test-Retest reliability of
the Hospital Anxiety and Depression Scale - Anxiety subscale (HADS-A). We could take
all kinds of other scores where ICC values and a
\href{https://en.wikipedia.org/wiki/Minimal_important_difference}{minimally clinically important difference (MCID)}
is given. Briefly, the MCID is the smallest change in a score that is considered
important to the patient. For example, a 5\% change in BMI is (in some populations)
considered meaningful.

Specifically, we:

\begin{itemize}
\tightlist
\item
  Simulate two correlated measurements at two time points (TP1 and TP2)
  to get predetermined ICC (\(=\rho\)).
\item
  Calculate the Intraclass Correlation Coefficient (ICC).
\item
  Compare the Minimally Clinically Important Difference (MCID) to prediction intervals.
\item
  Visualize how often a clinically meaningful change of 1.68 points is
  detected, even if no real change has occurred.
\end{itemize}

The code can be found \href{https://github.com/jdegenfellner/ICC_MCID/blob/main/ICC_MCID.R}{here}
and in the github repo of the script. In the code, the sources for the ICC and MCID are
cited.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ICC and Test{-}Retest{-}Reliability}

\FunctionTok{library}\NormalTok{(pacman)}
\FunctionTok{p\_load}\NormalTok{(tidyverse, lme4, conflicted, psych, MASS)}

\CommentTok{\# MCID Minimal Clinically Important Difference{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\CommentTok{\# HADS score{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# The Hospital Anxiety and Depression Scale }

\CommentTok{\# Test{-}Retest{-}Reliability:}
\CommentTok{\# https://doi.org/10.1016/S1361{-}9004(02)00029{-}8}

\CommentTok{\# Use the numbers from here (Table 1):}
\CommentTok{\# https://www.sciencedirect.com/science/article/abs/pii/S1361900402000298}
\CommentTok{\# for demonstration purposes.}

\CommentTok{\# Minimal Clinically Important Difference (MCID) for HADS{-}A:}
\CommentTok{\# https://pmc.ncbi.nlm.nih.gov/articles/PMC2459149/}
\CommentTok{\# Not exactly the same population as shift workers, but suffices for demonstration purposes.}
\CommentTok{\# MCID HADS anxiety score and 1.68 (1.48–1.87)}

\CommentTok{\# Simplification: Score is deemed to be continuous.}

\CommentTok{\# Create 2 correlated measurements:}
\CommentTok{\# Use HADS{-}A Anxiety subscale}
\CommentTok{\# Use n=100, instead of n=24 for more stability}

\NormalTok{sigma1 }\OtherTok{\textless{}{-}} \FloatTok{3.93}  \CommentTok{\# Standard deviation of variable 1}
\NormalTok{sigma2 }\OtherTok{\textless{}{-}} \FloatTok{3.52}  \CommentTok{\# Standard deviation of variable 2}
\NormalTok{rho }\OtherTok{\textless{}{-}} \FloatTok{0.82}    \CommentTok{\# Correlation}
\NormalTok{cov\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(sigma1}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{, rho }\SpecialCharTok{*}\NormalTok{ sigma1 }\SpecialCharTok{*}\NormalTok{ sigma2,}
\NormalTok{                       rho }\SpecialCharTok{*}\NormalTok{ sigma1 }\SpecialCharTok{*}\NormalTok{ sigma2, sigma2}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{), }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{188}\NormalTok{)  }\CommentTok{\# For reproducibility}
\NormalTok{samples }\OtherTok{\textless{}{-}} \FunctionTok{mvrnorm}\NormalTok{(}\AttributeTok{n =}\NormalTok{ n, }\AttributeTok{mu =} \FunctionTok{c}\NormalTok{(}\FloatTok{7.92}\NormalTok{, }\FloatTok{7.83}\NormalTok{), }\AttributeTok{Sigma =}\NormalTok{ cov\_matrix)}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(samples)}
\FunctionTok{colnames}\NormalTok{(df) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"TP1"}\NormalTok{, }\StringTok{"TP2"}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(df, }\AttributeTok{main =} \StringTok{"Scatterplot of Multivariate Normal Samples"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"TP1"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"TP2"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{col =} \FunctionTok{rgb}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-13-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# https://en.wikipedia.org/wiki/Intraclass\_correlation\#Modern\_ICC\_definitions:\_simpler\_formula\_but\_positive\_bias}
\CommentTok{\# ICC should be the correlation within the group (i.e. patient)}

\FunctionTok{cor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{TP1, df}\SpecialCharTok{$}\NormalTok{TP2, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{) }\CommentTok{\# \textasciitilde{}0.8{-}0.9}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8184881
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ICC}\NormalTok{(df) }\CommentTok{\# 0.82}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## boundary (singular) fit: see help('isSingular')
\end{verbatim}

\begin{verbatim}
## Call: ICC(x = df)
## 
## Intraclass correlation coefficients 
##                          type  ICC  F df1 df2       p lower bound upper bound
## Single_raters_absolute   ICC1 0.82 10  99 100 5.6e-26        0.74        0.87
## Single_random_raters     ICC2 0.82 10  99  99 8.7e-26        0.74        0.87
## Single_fixed_raters      ICC3 0.82 10  99  99 8.7e-26        0.74        0.87
## Average_raters_absolute ICC1k 0.90 10  99 100 5.6e-26        0.85        0.93
## Average_random_raters   ICC2k 0.90 10  99  99 8.7e-26        0.85        0.93
## Average_fixed_raters    ICC3k 0.90 10  99  99 8.7e-26        0.85        0.93
## 
##  Number of subjects = 100     Number of Judges =  2
## See the help file for a discussion of the other 4 McGraw and Wong estimates,
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# check manually}
\NormalTok{df\_mod }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{id =} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n, df}\SpecialCharTok{$}\NormalTok{TP1, df}\SpecialCharTok{$}\NormalTok{TP2)}
\FunctionTok{names}\NormalTok{(df\_mod) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"id"}\NormalTok{, }\StringTok{"TP1"}\NormalTok{, }\StringTok{"TP2"}\NormalTok{)}
\NormalTok{df\_mod\_long }\OtherTok{\textless{}{-}}\NormalTok{ df\_mod }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols =} \FunctionTok{c}\NormalTok{(TP1, TP2), }
                                       \AttributeTok{names\_to =} \StringTok{"time\_point"}\NormalTok{, }
                                       \AttributeTok{values\_to =} \StringTok{"score"}\NormalTok{)}
\NormalTok{mod }\OtherTok{\textless{}{-}}\NormalTok{ lme4}\SpecialCharTok{::}\FunctionTok{lmer}\NormalTok{(score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ time\_point }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{id), }\AttributeTok{data =}\NormalTok{ df\_mod\_long)}
\NormalTok{variance\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{summary}\NormalTok{(mod)}\SpecialCharTok{$}\NormalTok{varcor)}
\CommentTok{\# ICC=}
\NormalTok{variance\_df}\SpecialCharTok{$}\NormalTok{sdcor[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ (variance\_df}\SpecialCharTok{$}\NormalTok{sdcor[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ variance\_df}\SpecialCharTok{$}\NormalTok{sdcor[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\CommentTok{\# \textasciitilde{}0.9}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8170566
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# cor and ICC are very very similar, should actually be identical.}

\CommentTok{\#data.frame(TP1 = df$TP1, TP2 = df$TP2) \%\textgreater{}\% }
\CommentTok{\#  ggplot(aes(x = TP1, y = TP2)) +}
\CommentTok{\#  geom\_point() +}
\CommentTok{\#  xlab("Measurement of patients at time point 1") +}
\CommentTok{\#  ylab("Measurement of the same patients at time point 2")}

\CommentTok{\# Range for HADS{-}A should be 0{-}21 }
\CommentTok{\# (according to "The Hospital Anxiety and Depression Scale, Zigmond \& Snaith, 1983")}

\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{TP1 =}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{TP1, }\AttributeTok{TP2 =}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{TP2) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(TP1 }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(TP2 }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# negative not possible}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(TP1 }\SpecialCharTok{\textless{}=} \DecValTok{21}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(TP2 }\SpecialCharTok{\textless{}=} \DecValTok{21}\NormalTok{) }\CommentTok{\# max. score is 21}
\NormalTok{df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          TP1       TP2
## 1  13.003089 14.539674
## 2   6.980669  9.312346
## 3  17.751972 12.957041
## 4  10.344489  6.995323
## 5   7.861347  7.568915
## 6  12.892886 11.703021
## 7   5.478497  7.952075
## 8   9.583384  7.515242
## 9   7.519451  4.043160
## 10 11.499240 11.652541
## 11  6.468033  6.660218
## 12  6.048513  3.471018
## 13  7.697834  9.065112
## 14 12.254369  8.811619
## 15  1.614857  4.614998
## 16 10.619077 10.125575
## 17  9.419930  8.518226
## 18  2.937867  4.456727
## 19  8.236834 11.196117
## 20  8.954668 12.675367
## 21 12.320423 12.768905
## 22 12.314754 10.081370
## 23  2.160930  6.959311
## 24  6.832022  6.613443
## 25  1.093221  4.571882
## 26  9.725573  9.440133
## 27  1.355585  4.171266
## 28  7.752631  9.028429
## 29  8.764755  5.020493
## 30  6.347606  3.694110
## 31  5.375775  4.932552
## 32 11.278457 10.079779
## 33  6.740993  6.092677
## 34  5.812009  4.668937
## 35  4.349329  6.225931
## 36  9.895140 12.126645
## 37 11.148574  9.213335
## 38  2.047422  2.430490
## 39  6.486131  6.032311
## 40  5.645763  7.611138
## 41  6.726079 10.071178
## 42  5.755609  7.947849
## 43 10.642786  9.117806
## 44  5.141220  5.304112
## 45  2.642085  1.933020
## 46  7.684671  6.640758
## 47  9.262502  8.538370
## 48 16.254728 15.559716
## 49  7.156983  6.978574
## 50 12.081541 10.935277
## 51 11.764108  9.705782
## 52 11.558231 10.001998
## 53  7.207230  8.702822
## 54 13.271195 12.305426
## 55  8.662632  9.794167
## 56  7.202986  3.372489
## 57  5.857393 10.673803
## 58 12.606715  8.961083
## 59 11.081861 13.549278
## 60  4.900769  5.337160
## 61 15.309336 11.034889
## 62 14.589373 13.720623
## 63 13.671753 10.925029
## 64 12.180305 12.781404
## 65  1.762711  5.561035
## 66  3.140391  6.372191
## 67  5.492213  5.996299
## 68  4.466991  8.914347
## 69  2.502974  2.742313
## 70 12.667048  9.000329
## 71  4.580641  6.028937
## 72 11.858807 10.368234
## 73  4.537198  2.709857
## 74  7.419888 10.998858
## 75  4.879237  4.827545
## 76 13.618764  9.062266
## 77 14.472807 14.418930
## 78  7.952580  7.896180
## 79  1.912410  3.428163
## 80  7.801004  2.616797
## 81 10.336987 11.858491
## 82  8.417477 10.399787
## 83  5.491992  7.532053
## 84  7.596043  3.712851
## 85  6.912368  8.655686
## 86  6.201155  2.107871
## 87 11.707088 13.145075
## 88  3.443512  1.810893
## 89 12.406231 12.175912
## 90  7.231295  8.403967
## 91 11.070856 10.877902
## 92 14.508512 13.754604
## 93  9.936188 10.610818
## 94  6.590862  3.507825
## 95 11.660322 10.722280
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(TP2 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ TP1, }\AttributeTok{data =}\NormalTok{ df)}
\NormalTok{pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(mod, df, }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{)}

\CommentTok{\# How wide are the prediction intervals for a patient?}
\FunctionTok{as.data.frame}\NormalTok{(pred) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{width\_prediction\_interval =}\NormalTok{ upr }\SpecialCharTok{{-}}\NormalTok{ lwr) }\CommentTok{\# width of the prediction interval 8{-}10 points!}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          fit         lwr       upr width_prediction_interval
## 1  11.517789  7.32000445 15.715573                  8.395568
## 2   7.260698  3.09356695 11.427829                  8.334262
## 3  14.874649 10.57640522 19.172893                  8.596488
## 4   9.638494  5.46784345 13.809144                  8.341301
## 5   7.883226  3.71851506 12.047937                  8.329422
## 6  11.439889  7.24365214 15.636126                  8.392473
## 7   6.198852  2.02213714 10.375568                  8.353431
## 8   9.100489  4.93366030 13.267318                  8.333658
## 9   7.641549  3.47617950 11.806918                  8.330738
## 10 10.454757  6.27494432 14.634571                  8.359626
## 11  6.898329  2.72869927 11.067959                  8.339260
## 12  6.601781  2.42951087 10.774051                  8.344541
## 13  7.767643  3.60266181 11.932624                  8.329962
## 14 10.988538  6.80055090 15.176525                  8.375974
## 15  3.467747 -0.76481930  7.700313                  8.465132
## 16  9.832593  5.66013066 14.005055                  8.344925
## 17  8.984947  4.81870889 13.151186                  8.332477
## 18  4.402947  0.19450442  8.611390                  8.416885
## 19  8.148648  3.98424793 12.313048                  8.328800
## 20  8.656066  4.49106133 12.821072                  8.330010
## 21 11.035230  6.84644646 15.224014                  8.377568
## 22 11.031223  6.84250820 15.219938                  8.377430
## 23  3.853751 -0.36823502  8.075737                  8.443972
## 24  7.155623  2.98785021 11.323396                  8.335546
## 25  3.099016 -1.14446756  7.342499                  8.486967
## 26  9.200999  5.03359021 13.368407                  8.334817
## 27  3.284474 -0.95341998  7.522367                  8.475787
## 28  7.806378  3.64149615 11.971259                  8.329763
## 29  8.521822  4.35713015 12.686514                  8.329383
## 30  6.813202  2.64286933 10.983535                  8.340666
## 31  6.126241  1.94861984 10.303862                  8.355242
## 32 10.298692  6.12094325 14.476441                  8.355497
## 33  7.091277  2.92307764 11.259477                  8.336399
## 34  6.434603  2.26060789 10.608598                  8.347990
## 35  5.400673  1.21224884  9.589097                  8.376848
## 36  9.320861  5.15268035 13.489042                  8.336361
## 37 10.206881  6.03027765 14.383484                  8.353206
## 38  3.773515 -0.45059795  7.997629                  8.448227
## 39  6.911122  2.74159427 11.080650                  8.339056
## 40  6.317088  2.14177936 10.492397                  8.350617
## 41  7.080735  2.91246298 11.249007                  8.336544
## 42  6.394735  2.22030395 10.569166                  8.348862
## 43  9.849352  5.67672294 14.021982                  8.345259
## 44  5.960440  1.78063088 10.140249                  8.359619
## 45  4.193867 -0.01952182  8.407256                  8.426777
## 46  7.758338  3.59333195 11.923345                  8.330013
## 47  8.873666  4.70791894 13.039413                  8.331494
## 48 13.816287  9.55673194 18.075843                  8.519111
## 49  7.385330  3.21887319 11.551787                  8.332914
## 50 10.866371  6.68040625 15.052336                  8.371929
## 51 10.641986  6.45950156 14.824470                  8.364969
## 52 10.496456  6.31606656 14.676846                  8.360780
## 53  7.420848  3.25456616 11.587130                  8.332564
## 54 11.707306  7.50560608 15.909006                  8.403400
## 55  8.449634  4.28506471 12.614202                  8.329138
## 56  7.417848  3.25155183 11.584145                  8.332593
## 57  6.466683  2.29303270 10.640334                  8.347301
## 58 11.237603  7.04521442 15.429991                  8.384777
## 59 10.159723  5.98368848 14.335757                  8.352069
## 60  5.790471  1.60824613  9.972696                  8.364450
## 61 13.148015  8.90959977 17.386429                  8.476830
## 62 12.639092  8.41504000 16.863143                  8.448103
## 63 11.990450  7.78250179 16.198399                  8.415897
## 64 10.936184  6.74907482 15.123294                  8.374219
## 65  3.572261 -0.65735481  7.801876                  8.459231
## 66  4.546106  0.34090074  8.751312                  8.410411
## 67  6.208548  2.03195085 10.385144                  8.353194
## 68  5.483845  1.29682048  9.670870                  8.374049
## 69  4.095533 -0.12027142  8.311337                  8.431609
## 70 11.280250  7.08707078 15.473429                  8.386359
## 71  5.564181  1.37846891  9.749893                  8.371425
## 72 10.708926  6.52543503 14.892417                  8.366982
## 73  5.533472  1.34726300  9.719682                  8.372419
## 74  7.571170  3.40554231 11.736798                  8.331256
## 75  5.775251  1.59280130  9.957701                  8.364900
## 76 11.952994  7.74589920 16.160088                  8.414189
## 77 12.556694  8.33482530 16.778563                  8.443737
## 78  7.947716  3.78312039 12.112312                  8.329192
## 79  3.678079 -0.54861400  7.904772                  8.453386
## 80  7.840572  3.67577039 12.005373                  8.329602
## 81  9.633192  5.46258745 13.803796                  8.341208
## 82  8.276340  4.11193632 12.440744                  8.328808
## 83  6.208392  2.03179294 10.384990                  8.353197
## 84  7.695690  3.53049953 11.860881                  8.330381
## 85  7.212418  3.04500055 11.379836                  8.334835
## 86  6.709680  2.53843261 10.880928                  8.342495
## 87 10.601680  6.41978859 14.783572                  8.363783
## 88  4.760375  0.55978683  8.960963                  8.401176
## 89 11.095886  6.90604714 15.285724                  8.379677
## 90  7.437859  3.27165782 11.604060                  8.332402
## 91 10.151944  5.97600166 14.327886                  8.351884
## 92 12.581933  8.35939957 16.804466                  8.445066
## 93  9.349877  5.18149616 13.518258                  8.336761
## 94  6.985154  2.81619604 11.154112                  8.337916
## 95 10.568622  6.38720944 14.750034                  8.362825
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Example:}
\FunctionTok{predict}\NormalTok{(mod, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{TP1 =} \DecValTok{10}\NormalTok{), }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{) }\CommentTok{\# 95\% prediction interval for a patient with a score of 10 at time point 1.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 9.394984 5.226282 13.56369
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FloatTok{13.56369} \SpecialCharTok{{-}} \FloatTok{5.226282}\NormalTok{)}\SpecialCharTok{/}\FloatTok{1.68}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.962743
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Prediction interval width is \textasciitilde{}5 times our minimally clinically important }
\CommentTok{\# change of 1.68 for HADS{-}A.}

\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ TP1, }\AttributeTok{y =}\NormalTok{ TP2)) }\SpecialCharTok{+}
  \CommentTok{\# Color points conditionally}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \FunctionTok{ifelse}\NormalTok{(TP2 }\SpecialCharTok{\textgreater{}}\NormalTok{ TP1 }\SpecialCharTok{+} \FloatTok{1.68} \SpecialCharTok{|}\NormalTok{ TP2 }\SpecialCharTok{\textless{}}\NormalTok{ TP1 }\SpecialCharTok{{-}} \FloatTok{1.68}\NormalTok{, }\StringTok{"red"}\NormalTok{, }\StringTok{"black"}\NormalTok{))) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"red"} \OtherTok{=} \StringTok{"red"}\NormalTok{, }\StringTok{"black"} \OtherTok{=} \StringTok{"black"}\NormalTok{), }\AttributeTok{guide =} \StringTok{"none"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =}\NormalTok{ mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{], }\AttributeTok{slope =}\NormalTok{ mod}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_ribbon}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{ymin =}\NormalTok{ pred[,}\DecValTok{2}\NormalTok{], }\AttributeTok{ymax =}\NormalTok{ pred[,}\DecValTok{3}\NormalTok{]), }\AttributeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"HADS{-}A and 95\% Prediction Interval for TP2"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"green"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =} \FloatTok{1.68}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =} \SpecialCharTok{{-}}\FloatTok{1.68}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-13-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# How often is TP2 within the MCIC of 1.68 points?{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{abs\_diff }\OtherTok{\textless{}{-}} \FunctionTok{abs}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{TP1 }\SpecialCharTok{{-}}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{TP2)}
\FunctionTok{hist}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{abs\_diff)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \FloatTok{1.68}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-13-3.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{abs\_diff }\SpecialCharTok{\textgreater{}} \FloatTok{1.68}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(}\FunctionTok{table}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{abs\_diff }\SpecialCharTok{\textgreater{}} \FloatTok{1.68}\NormalTok{)) }\CommentTok{\# }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##     FALSE      TRUE 
## 0.5368421 0.4631579
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}\textgreater{} in \textasciitilde{}46\% of cases we detect a minimally clinically important change of 1.68 points.}
\CommentTok{\# even though the underlying truth did not change.}

\CommentTok{\# This result is near random guessing}
\end{Highlighting}
\end{Shaded}

The example shows that for the given value of ICC (\(>0.8\)) and MCID, the test retest reliability
is near random guessing with respect to detecting a change, since the second prediction is
very often outside the MCID (red dashed lines). Or in short: Even if Mary measures twice
with this ICC value, she will detect a clinically meaningful change in almost half of the cases,
although the underlying
truth did not change.

One could play around a little bit with the parameters here
(and maybe make the argument more rigorous),
but my guess would be that the main message remains stable.

What do you think? Can you find literature or logical arguments against this
simulation? I would be pleased to hear your thoughts.

What could come to the rescue of this systematic problem?
I think one must consider more reliable scales simultaneously in order
to make decicisions, specifically to determine if a change occured.

See \hyperref[exercise4]{exercise 4} to try the above code with a score of your choosing.

\subsubsection{Standard Error of Measurement (SEM)}\label{standard-error-of-measurement-sem}

Above, we defined the overall ICC as:

\[ICC = \frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 + \sigma_{\varepsilon}^2}\]

The SEM is defined as: \(\sqrt{\sigma_{\varepsilon}^2}\).

This is a \textbf{measure for the precision of the model}. If this number is small,
we know the true but unknown score (\(\eta\)) very precisely. As we have seen, for the
\(ICC_{agreement}\) the error term includes the rater variability \(\sigma_{rater}\).

For ICC2 and 3 the model is the \textbf{same} and:

\[Y_{ij} = \eta_i + \beta_j + \varepsilon_i\]

For \(ICC_{agreement}\), the SEM is then:
\[\sigma_{Y_i}^2 = \sigma_{\eta}^2 + \underbrace{\sigma_{\text{rater}}^2 + \sigma_{\varepsilon}^2}_{SEM_{agreement}^2}\]

For \(ICC_{consistency}\), the SEM is then:
\[\sigma_{Y_i}^2 = \sigma_{\eta}^2 + \underbrace{\sigma_{\varepsilon}^2}_{SEM_{consistency}^2}\]

And since ICC 2 and 3 are based on the same model:
\[SEM_{consistency} \le SEM_{agreement}\]
(equality if there is no bias)

This yields the \textbf{first method} of getting the SEM: Estimate the
model (as we did above) and take the square root of the respective error term
(with or without the rater variability).

One can also show that we can find the \(SEM_{consistency}\) by using
the standard deviation of the differences between the two measurements
of Peter and Mary:

\textbf{We verify this immediately}:

\[SEM_{consistency} = \frac{SD_{difference}}{\sqrt{2}}\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(ROM }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ ID) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ Rater), }\AttributeTok{data =}\NormalTok{ df\_long\_bias)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{VarCorr}\NormalTok{(mod))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Groups   Name        Std.Dev.
##  ID       (Intercept) 16.4585 
##  Rater    (Intercept)  2.4886 
##  Residual              6.8961
\end{verbatim}

\[SEM_{consistency} = \sigma_{residual} = 6.8961\]

Let's calculate the \textbf{SEM from the differences} between the two measurements:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# SEM from differences}
\FunctionTok{sd}\NormalTok{(df\_long\_bias}\SpecialCharTok{$}\NormalTok{ROM[df\_long\_bias}\SpecialCharTok{$}\NormalTok{Rater }\SpecialCharTok{==} \StringTok{"ROMas.Mary"}\NormalTok{] }\SpecialCharTok{{-}}
\NormalTok{   df\_long\_bias}\SpecialCharTok{$}\NormalTok{ROM[df\_long\_bias}\SpecialCharTok{$}\NormalTok{Rater }\SpecialCharTok{==} \StringTok{"ROMas.Peter"}\NormalTok{]) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.896154
\end{verbatim}

This is a perfect match!

\subsubsection{Bland-Altman Plot}\label{bland-altman-plot}

The Bland-Altman plot (see 5.4.2.2. in the book) is a graphical method to compare
two measurements techniques or raters. The goal is to spot systematic differences
between the two
methods/raters. On the x axis, we plot the average of the two measurements (proxy for the true value)
and on the y axis the difference between the two measurements. So, we could
for instance see larger variability in points with higher average values,
indicating that Peter and Mary disagree more for higher values.

Let's quickly draw one and explain it:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(BlandAltmanLeh)}
\FunctionTok{library}\NormalTok{(data.table)}
\NormalTok{df\_long\_bias }\OtherTok{\textless{}{-}} \FunctionTok{as.data.table}\NormalTok{(df\_long\_bias)}
\CommentTok{\# https://cran.r{-}project.org/web/packages/BlandAltmanLeh/BlandAltmanLeh.pdf}
\FunctionTok{bland.altman.plot}\NormalTok{(df\_long\_bias[Rater }\SpecialCharTok{==} \StringTok{"ROMas.Mary"}\NormalTok{, ]}\SpecialCharTok{$}\NormalTok{ROM,}
\NormalTok{                  df\_long\_bias[Rater }\SpecialCharTok{==} \StringTok{"ROMas.Peter"}\NormalTok{, ]}\SpecialCharTok{$}\NormalTok{ROM,}
                  \AttributeTok{two =} \FloatTok{1.96}\NormalTok{,}
                  \AttributeTok{mode =} \DecValTok{1}\NormalTok{,}
                  \AttributeTok{conf.int =} \FloatTok{0.94}
\NormalTok{                  )}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-16-1.pdf}}

\begin{verbatim}
## NULL
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# "two": Lines are drawn "two" standard deviations from mean differences. }
\CommentTok{\# This defaults to 1.96 for proper 95 percent confidence interval }
\CommentTok{\# estimation but can be set to 2.0 for better agreement with e. g. }
\CommentTok{\# the Bland Altman publication. }

\CommentTok{\# "mode": if 1 then difference group1 minus group2 is used,}
\CommentTok{\# if 2 then group2 minus group1 is used. Defaults to 1.}

\CommentTok{\# "conf.int": confidence interval for the mean difference}
\CommentTok{\# and the limits of agreement.}

\CommentTok{\# The red dotted line is the mean difference $\textbackslash{}bar\{d\}$ }
\CommentTok{\# between the two measurements.}

\CommentTok{\# see ?bland.altman.plot}
\end{Highlighting}
\end{Shaded}

The \emph{Limits of Agreement} (LoA) are derived from data and represent
the ``usual'' values for the difference between the two measurements.
Basically, we only need information from the paired \(t\)-test.
The \(1.96\) in the formula is (as always)
a hint that we assume the difference is normally distributed. This is not
always the case.

The formula for the LoA is (due to the connection between the SEM and the
SD of the differences above):

\[LoA = \bar{d} \pm 1.96 \cdot SD_{difference} = 
\bar{d} \pm 1.96 \cdot \sqrt{2} \cdot SEM_{consistency}\]

Let us not get confused by the name. Just because a data point is shown
within the LoA, it does not mean that it is a good measurement. Maybe \(\pm 20\) degrees
(as visible in the plot) is unsifficient agreement for practical purposes.
The LoA is a statistical measure, not a clinical one.

To remember the fact that a normal distribution is assumed for the differences
\(\bar{d}\), we draw the limits of agreement for our data:

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-17-1.pdf}}

\(\bar{d}=3.87\) (before the bias introduction, Mary was on average 1.2 lower)
There should be approximately \(95\%\) of the differences
between the two measurements within the limits of agreement.

See also \hyperref[exercise6]{exercise 6}.

\subsubsection{Example of a Reliability Study}\label{example_RELStudy}

Let's try to verify some of the ICCs calculated in
\href{https://www.biorxiv.org/content/10.1101/2024.06.23.600286v2.abstract}{this paper}.

The title of the paper is ``Between-day reliability of local
and global muscle-tendon unit assessments in female athletes
whilst controlling for menstrual cycle phase''.

It takes a while to find a study that provides the data. Kindly, the authors
provide raw data \href{https://figshare.com/articles/dataset/Test-retest_dataset_xlsx/26477206?file=48128929}{here}.

Some comments after a quick glance at the paper:

\begin{itemize}
\item
  One thing you should avoid is to write results in the methods section as
  is done in lines 152-154 of the \href{https://www.biorxiv.org/content/10.1101/2024.06.23.600286v2.full.pdf}{pdf}.
  First we describe what we did, then we show the results.
\item
  The next thing to avoid is testing for normality. For seventeen participants,
  the power of the test might be low - see Figure 1a/b \href{https://www.nbi.dk/~petersen/Teaching/Stat2017/Power_Comparisons_of_Shapiro-Wilk_Kolmogorov-Smirn.pdf}{here}.
\item
  Apparently, there was no power calculation for the ICCs or the paired \(t\)-test.
  As a consequence, results (for instance for the \(t\)-test) are to be interpreted exploratively.
\item
  Multiple testing is not considered.
  From the first \(28\) \(p\)-values in Table 1 and 2 of the paper, two are ``significant''
  (\(p=0.049\), both marked with a star of course),
  which is well within the expected number of false positives. Remember,
  under \(H_0\) every \(20\)th test is ``significant''.
  Fortunately, the authors do not overinterpret the results and
  do not mention ``significance'' in the results or discussion.
\end{itemize}

Look at Table 1 in the paper and consider the variable \emph{Planar flexion MVC (N.m)}.
We want to replicate the results in the first line
(except for \(p\)-values and effect size \(d\)).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(pacman)}
\FunctionTok{conflicts\_prefer}\NormalTok{(rethinking}\SpecialCharTok{::}\NormalTok{logit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [conflicted] Will prefer rethinking::logit over any other package.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{p\_load}\NormalTok{(}
\NormalTok{  tidyverse,}
\NormalTok{  readxl,}
\NormalTok{  psych)}

\CommentTok{\# Read file from github}
\NormalTok{tmp }\OtherTok{\textless{}{-}} \FunctionTok{tempfile}\NormalTok{(}\AttributeTok{fileext =} \StringTok{".xlsx"}\NormalTok{)}
\FunctionTok{download.file}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/jdegenfellner/Script\_QM3\_ZHAW/main/data/Chapter\_Rel\_Val/2\_bioxar/Test{-}retest\_dataset.xlsx"}\NormalTok{, }
              \AttributeTok{destfile =}\NormalTok{ tmp, }\AttributeTok{mode =} \StringTok{"wb"}\NormalTok{)}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{suppressMessages}\NormalTok{(}\FunctionTok{read\_xlsx}\NormalTok{(tmp, }\AttributeTok{sheet =} \StringTok{"Sheet1"}\NormalTok{, }\AttributeTok{skip =} \DecValTok{1}\NormalTok{)))}
\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 113
##   Participant `Displacement (mm)`  ...3 `Passive displacement (mm)`  ...5
##         <dbl>               <dbl> <dbl>                       <dbl> <dbl>
## 1           1               13.9  14.2                         4.46  4.65
## 2           2               20.5  14.8                         5.32  4.58
## 3           3                8.81  8.23                        2.08  2.31
## 4           4               12.8  10.2                         5.17  5.11
## 5           5               22.4  21.5                         6.97  6.67
## 6           6               19.0  18.7                         5.12  6.19
## # i 108 more variables: `Corr displacement (mm)` <dbl>, ...7 <dbl>,
## #   `Strain (%)` <dbl>, ...9 <dbl>, `Plantar flexion moment (N.m)` <dbl>,
## #   ...11 <dbl>, `AT force (N)` <dbl>, ...13 <dbl>, `AtK all (N/mm)` <dbl>,
## #   ...15 <dbl>, `ATk low (N/mm)` <dbl>, ...17 <dbl>, `ATk high (N/mm)` <dbl>,
## #   ...19 <dbl>, `NATk all (N/strain)` <dbl>, ...21 <dbl>,
## #   `NATk low (N/strain)` <dbl>, ...23 <dbl>, `NATk high (N/strain)` <dbl>,
## #   `Norm ATk 50-100 2` <dbl>, `ATk index (N/strain)` <dbl>, ...27 <dbl>, ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#colnames(df)}

\NormalTok{df\_1 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Plantar flexion moment (N.m)}\StringTok{\textasciigrave{}}\NormalTok{, }\StringTok{\textasciigrave{}}\AttributeTok{...11}\StringTok{\textasciigrave{}}\NormalTok{)}
\FunctionTok{head}\NormalTok{(df\_1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   `Plantar flexion moment (N.m)` ...11
##                            <dbl> <dbl>
## 1                          122.  118. 
## 2                          120.  142. 
## 3                           85.5  82.4
## 4                          114.  102. 
## 5                          116.  115. 
## 6                          119.  114.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#tail(df\_1)}
\FunctionTok{dim}\NormalTok{(df\_1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17  2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df\_1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{\textasciigrave{}}\AttributeTok{Plantar flexion moment (N.m)}\StringTok{\textasciigrave{}}\NormalTok{, }\AttributeTok{y =} \StringTok{\textasciigrave{}}\AttributeTok{...11}\StringTok{\textasciigrave{}}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Scatterplot of Plantar flexion moment"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Plantar flexion moment (N.m) {-} Session 1"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Plantar flexion moment (N.m) {-} Session 2"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Chapter_01_Reliability_Validity_files/figure-latex/unnamed-chunk-18-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Looks rather nice}
\CommentTok{\# would be interesting what influence the largest 2 and the smallest observation have}

\FunctionTok{colnames}\NormalTok{(df\_1) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"test"}\NormalTok{, }\StringTok{"retest"}\NormalTok{)}

\CommentTok{\# Mean Session 1}
\FunctionTok{mean}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{test, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 124.18
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 124.18 check}
\FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{test, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.91872
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 15.91872 check}

\CommentTok{\# Mean Session 2}
\FunctionTok{mean}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{retest, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 126.1748
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 126.1748 check}
\FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{retest, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20.41306
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 20.41306}

\CommentTok{\# Change}
\FunctionTok{mean}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{retest }\SpecialCharTok{{-}}\NormalTok{ df\_1}\SpecialCharTok{$}\NormalTok{test, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.99477
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1.99477 check}
\FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{retest }\SpecialCharTok{{-}}\NormalTok{ df\_1}\SpecialCharTok{$}\NormalTok{test, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.160476
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 8.160476 check}

\CommentTok{\# The p{-}value column is not needed, as well as the d (effect size)}

\CommentTok{\# create long format for ICC calculation}
\NormalTok{df\_long }\OtherTok{\textless{}{-}}\NormalTok{ df\_1 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols =} \FunctionTok{everything}\NormalTok{(), }\AttributeTok{names\_to =} \StringTok{"Timepoint"}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{"value"}\NormalTok{) }
\FunctionTok{head}\NormalTok{(df\_long)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   Timepoint value
##   <chr>     <dbl>
## 1 test      122. 
## 2 retest    118. 
## 3 test      120. 
## 4 retest    142. 
## 5 test       85.5
## 6 retest     82.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{psych}\SpecialCharTok{::}\FunctionTok{ICC}\NormalTok{(df\_1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call: psych::ICC(x = df_1)
## 
## Intraclass correlation coefficients 
##                          type  ICC  F df1 df2       p lower bound upper bound
## Single_raters_absolute   ICC1 0.90 19  16  17 8.4e-08        0.75        0.96
## Single_random_raters     ICC2 0.90 19  16  16 1.7e-07        0.75        0.96
## Single_fixed_raters      ICC3 0.90 19  16  16 1.7e-07        0.75        0.96
## Average_raters_absolute ICC1k 0.95 19  16  17 8.4e-08        0.86        0.98
## Average_random_raters   ICC2k 0.95 19  16  16 1.7e-07        0.86        0.98
## Average_fixed_raters    ICC3k 0.95 19  16  16 1.7e-07        0.86        0.98
## 
##  Number of subjects = 17     Number of Judges =  2
## See the help file for a discussion of the other 4 McGraw and Wong estimates,
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# In Table 1, we find the values for ICC1k: 0.95 (95\% CI: 0.86{-}0.98)}

\CommentTok{\# Standard error of measurement:}
\CommentTok{\# SEM = SD\_difference/sqrt(2)}
\FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{retest }\SpecialCharTok{{-}}\NormalTok{ df\_1}\SpecialCharTok{$}\NormalTok{test, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.770328
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 5.770328 vs. 4.2 in the paper}

\CommentTok{\# In "Measurement in Medicine", p. 112, the authors warn against}
\CommentTok{\# the formula the paper used to calculate the SEM:}
\CommentTok{\# SEM = SD\_pooled*sqrt(1{-}ICC)}
\NormalTok{SD\_pooled }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((}\FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{test, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+} \FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{retest, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}
\NormalTok{SEM }\OtherTok{\textless{}{-}}\NormalTok{ SD\_pooled}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}} \FloatTok{0.9477155}\NormalTok{)}
\NormalTok{SEM}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.185437
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# =4.185437 vs. 4.2 in the paper}

\CommentTok{\# Formula 5.7 in the book:}
\CommentTok{\# sigma\_y is the total variance}
\CommentTok{\# lets get the variance components with lmer:}
\FunctionTok{dim}\NormalTok{(df\_long)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 34  2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_long}\SpecialCharTok{$}\NormalTok{ID}\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\AttributeTok{each=}\DecValTok{2}\NormalTok{)}
\NormalTok{mod }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(value }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Timepoint }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{ID), }\AttributeTok{data =}\NormalTok{ df\_long)}
\FunctionTok{summary}\NormalTok{(mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed model fit by REML ['lmerMod']
## Formula: value ~ Timepoint + (1 | ID)
##    Data: df_long
## 
## REML criterion at convergence: 255.9
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.66018 -0.39028  0.00975  0.52172  1.76028 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  ID       (Intercept) 301.8    17.37   
##  Residual              33.3     5.77   
## Number of obs: 34, groups:  ID, 17
## 
## Fixed effects:
##               Estimate Std. Error t value
## (Intercept)    126.175      4.439  28.421
## Timepointtest   -1.995      1.979  -1.008
## 
## Correlation of Fixed Effects:
##             (Intr)
## Timeponttst -0.223
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# check ICC1k:}
\FloatTok{301.8}\SpecialCharTok{/}\NormalTok{(}\FloatTok{301.8} \SpecialCharTok{+} \FloatTok{33.3}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9477155
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0.9477155 check}

\CommentTok{\# Try with Timepoint as random effect (could be rater)}
\NormalTok{mod2 }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(value }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{ID) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{Timepoint), }\AttributeTok{data =}\NormalTok{ df\_long)}
\FunctionTok{summary}\NormalTok{(mod2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed model fit by REML ['lmerMod']
## Formula: value ~ (1 | ID) + (1 | Timepoint)
##    Data: df_long
## 
## REML criterion at convergence: 260.1
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.83032 -0.36357 -0.07451  0.46315  1.93042 
## 
## Random effects:
##  Groups    Name        Variance  Std.Dev.
##  ID        (Intercept) 301.74846 17.371  
##  Timepoint (Intercept)   0.03097  0.176  
##  Residual               33.29703  5.770  
## Number of obs: 34, groups:  ID, 17; Timepoint, 2
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   125.18       4.33   28.91
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}\textgreater{} sigma\_y = SD\_pooled = }
\FunctionTok{sqrt}\NormalTok{(}\FloatTok{301.8} \SpecialCharTok{+} \FloatTok{33.3}\NormalTok{) }\CommentTok{\# = 18.30574}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 18.30574
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# SEM = }
\FunctionTok{sqrt}\NormalTok{(}\FloatTok{301.8} \SpecialCharTok{+} \FloatTok{33.3}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}} \FloatTok{0.9477155}\NormalTok{) }\CommentTok{\# 4.18}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.185754
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# or this (if average measurements are meant, ICC1k)?}
\FunctionTok{sqrt}\NormalTok{(}\FloatTok{301.8} \SpecialCharTok{+} \FloatTok{33.3}\SpecialCharTok{/}\DecValTok{2}\NormalTok{) }\CommentTok{\# 17.84517}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17.84517
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# SEM = }
\FunctionTok{sqrt}\NormalTok{(}\FloatTok{301.8} \SpecialCharTok{+} \FloatTok{33.3}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}} \FloatTok{0.9477155}\NormalTok{) }\CommentTok{\# 4.08 (4.18 if ICC1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.080441
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# MCD, Minimally Detectable Difference:}
\CommentTok{\# (also known as Smallest Detectable Change, SDC)}
\CommentTok{\# MCD = }
\FloatTok{1.96} \SpecialCharTok{*} \FloatTok{4.185437} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 11.60144
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 11.6 check.}

\CommentTok{\# Coefficient of Variation:}
\CommentTok{\# The CV was calculated for each participant as (within{-}subject SD / mean) * 100, }
\CommentTok{\# with the mean of values from all participants used as the test{-}}
\CommentTok{\# retest CV (e.g., [24]).}

\NormalTok{df\_1}\SpecialCharTok{$}\NormalTok{mean\_i }\OtherTok{\textless{}{-}} \FunctionTok{rowMeans}\NormalTok{(df\_1, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\CommentTok{\# mean of test and retest for each person.}
\NormalTok{df\_1}\SpecialCharTok{$}\NormalTok{sd\_within\_i }\OtherTok{\textless{}{-}} \FunctionTok{abs}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{test }\SpecialCharTok{{-}}\NormalTok{ df\_1}\SpecialCharTok{$}\NormalTok{retest) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\NormalTok{df\_1}\SpecialCharTok{$}\NormalTok{cv\_i }\OtherTok{\textless{}{-}}\NormalTok{ (df\_1}\SpecialCharTok{$}\NormalTok{sd\_within\_i }\SpecialCharTok{/}\NormalTok{ df\_1}\SpecialCharTok{$}\NormalTok{mean\_i) }\SpecialCharTok{*} \DecValTok{100}

\CommentTok{\# Test{-}Retest CV}
\FunctionTok{mean}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{cv\_i, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.605028
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{cv\_i, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.964592
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 95\% CI:}
\FunctionTok{mean}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{cv\_i, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{)}\SpecialCharTok{*}\FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sd}\NormalTok{(df\_1}\SpecialCharTok{$}\NormalTok{cv\_i, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{17}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.195750 5.014306
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2.195750 5.014306 \# check}
\end{Highlighting}
\end{Shaded}

\subsection{Exercises}\label{exercises}

Solutions to the exercises can be found
\href{https://github.com/jdegenfellner/Script_QM3_ZHAW/tree/main/Solutions_Exercises}{here}.

\subsubsection{{[}E{]} Exercise 1}\label{exercise1}

Use the \(50\) ROM measurements from Peter and Mary (see above).

\begin{itemize}
\tightlist
\item
  Introduce biases of \(5\), \(15\) and \(35\) degrees in the data set. Mary should have systematically
  higher values than Peter.
\item
  Show in R that the correlation does not change.
\end{itemize}

\subsubsection{{[}M{]} Exercise 2}\label{exercise2}

Consider the \(50\) ROM measurements from Peter and Mary (see above) on the non affected side (nas).

\begin{itemize}
\tightlist
\item
  Regress Mary's measurements on Peter's measurements using the simple
  linear regression model in R.
\item
  How precisely can we predict Mary's measurements from Peter's, i.e.~analyse the resdiuals.
\item
  Calculate the mean absolute deviation MAE, i.e.~
  \[MAE = \frac{1}{n} \sum_{i=1}^n |ROM_i - \widehat{ROM}_i|\]
  where \(ROM_i\) is the true value and \(\widehat{ROM}_i\) is the model-predicted value.
\end{itemize}

\subsubsection{{[}E{]} Exercise 3}\label{exercise3}

\begin{itemize}
\tightlist
\item
  Draw the model hierarchy for the first model \hyperref[ICC]{above} (ICC1).
\end{itemize}

\subsubsection{{[}M{]} Exercise 4}\label{exercise4}

Go back to the \hyperref[badnews]{section} about the ICC and the example of the HADS-A.

\begin{itemize}
\tightlist
\item
  Find your own score, maybe one that is used in your field.
\item
  Find the miminally clinically important difference (MCID) for this score.
\item
  Execute the code above with your score and the MCID and see if
  the results are similar to the HADS-A example.
\end{itemize}

\subsubsection{{[}M{]} Exercise 5}\label{exercise5}

Consider the Bayesian model for the ICC2 and ICC3 above.

\begin{itemize}
\tightlist
\item
  Draw the model hierarchy for this model.
\end{itemize}

\subsubsection{{[}H{]} Exercise 6}\label{exercise6}

Read the following sections in the book \emph{Measurement in Medicine}:

\begin{itemize}
\tightlist
\item
  5.6.2.2 Bland-Altman method
\item
  8.5.3 Smallest detectable change (a change beyond the measurement error)
\item
  8.5.4.1 The concept of minimal important change
\item
  Be forgiving with the dichotomous writing style.
\end{itemize}

\subsubsection{{[}M{]} Exercise 7}\label{exercise7}

Go back to the 5 degree biased \(ROMs\) from Peter and Mary.

\begin{itemize}
\tightlist
\item
  Fit the Frequentist models for ICC1 and ICC2/3 again using \texttt{lmer}.
\item
  Perform model diagnostics (\texttt{check\_model}) for both models.
\item
  Also compare residuals and posterior predictive checks (PPC). You can
  plot the diagnostics separately, for example: \texttt{check\_model(mod1,\ check\ =\ "pp\_check")}.
\item
  What do you think about the model fit for the two models?
\item
  Which model do you prefer?
\end{itemize}

\subsubsection{{[}H{]} Exercise 8}\label{exercise8}

Introduce some outliers in the \(ROMs\) of Peter and Mary (50 participants).

\begin{itemize}
\tightlist
\item
  How do the outliers influence the ICC?
\item
  How do the outliers influence the model fit of the underlying statistical model?
\end{itemize}

\subsubsection{{[}M{]} Exercise 9}\label{exercise9}

Consider the example reliability study \hyperref[example_RELStudy]{above}.

\begin{itemize}
\tightlist
\item
  According to this \href{https://www.sciencedirect.com/science/article/pii/S1556370716000158?via\%3Dihub}{paper},
  did the authors choose the right ICC (ICC1k)?
  What can the chosen ICC be used for?
\item
  Verify the ICC for the ``Raw elongation (mm)'' in Table 1 of the paper.
\end{itemize}

\subsubsection{{[}H{]} Exercise 10}\label{exercise10}

We want to see where formula 5.7 for the SEM in the book comes from.
\[SEM = SD_{pooled} \cdot \sqrt{1 - ICC}\]

\begin{itemize}
\item
  We start with the formula for the (overall) ICC:
  \[ICC = \frac{\sigma_{\eta}^2}{\sigma_{\eta}^2 + \sigma_{\varepsilon}^2}\]
\item
  \(SEM = \sqrt{\sigma_{\varepsilon}^2}\)
\item
  Show that the formula for the SEM is equivalent to the one in
  the book by rewriting the ICC formula.
\end{itemize}

\subsection{eLearning}\label{elearning}

In this eLearning section, please study (the whole) chapter 6 on
\href{https://en.wikipedia.org/wiki/Validity_(statistics)}{validity} in the book (pages 150-196).
Here are some thoughts on the chapter:

\begin{itemize}
\tightlist
\item
  p.~153: ``Existing knowledge about the construct should drive the hypotheses.''
  This is an important point. It seems a good idea to apply our Baysian knowledge
  here. Often simply correlation tests or \(t\)-tests are used in this area.
  When doing so, it would be advantageous to define priors and use the Bayesian
  analysis we have covered previously.
\item
  p.~154: ``They emphasize that the crucial ingredient of validity involves the
  causal role of the construct in determining what value the measurement
  outcomes will take\ldots{}'' In my opinion, all these analyses should be done using
  causal inference. Richard McEleath's book contains a lot of information on this.
  But granted: We are at the very beginning on this topic, in the lecture and in wide
  areas of health-research.
\item
  You should be familiar with the different definitions of validity:
  face, content, concurrent, predictive, structural, convergent, discriminant,
  discriminiative validity.
\item
  p.~181 at the top: As you can imagine, this is a very important piece of information.
  We are not here to play ``significance''-bingo with ``hypotheses''. Ideally,
  we are searching for the truth and want to answer real questions
  (which is unfortunately not always attainable).
\item
  Figure 6.8. on p.~195. is worth remembering.
\end{itemize}

Additionally, look for at least two reliability and validity articles in your field
(either Reliabiilty alone or Reliability and Validity together) and try to understand what
they did. Did the authors provide code and data to aid reproducibility?

Please also go through the \href{https://jdegenfellner.github.io/Script_QM3_ZHAW/reliability-and-validity.html\#example_RELStudy}{last part}
of the reliability chapter in our skript.

\end{document}
